import { db } from '@/db';
import { bets } from '@/db/schema';

async function main() {
    const now = new Date();
    const thirtyDaysAgo = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);
    const sevenDaysAgo = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);

    // Helper function to generate random date in range
    const randomDate = (start: Date, end: Date) => {
        return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()));
    };

    // Helper function to get recent dates (70% in last 7 days)
    const getCreatedDate = () => {
        return Math.random() < 0.7 
            ? randomDate(sevenDaysAgo, now)
            : randomDate(thirtyDaysAgo, sevenDaysAgo);
    };

    const sampleBets = [
        // ========== SLOTS BETS (25 bets, gameIds: 1-25) ==========
        // Small bets - losses
        {
            userId: 1,
            gameId: 1,
            betAmount: 2.50,
            winAmount: 0,
            multiplier: 0,
            status: 'loss',
            betData: JSON.stringify({ lines: 20, coinValue: 0.125 }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        {
            userId: 3,
            gameId: 5,
            betAmount: 5.00,
            winAmount: 0,
            multiplier: 0,
            status: 'loss',
            betData: JSON.stringify({ lines: 25, coinValue: 0.20 }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        {
            userId: 5,
            gameId: 8,
            betAmount: 1.50,
            winAmount: 0,
            multiplier: 0,
            status: 'loss',
            betData: JSON.stringify({ lines: 15, coinValue: 0.10 }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        {
            userId: 7,
            gameId: 12,
            betAmount: 3.00,
            winAmount: 0,
            multiplier: 0,
            status: 'loss',
            betData: JSON.stringify({ lines: 20, coinValue: 0.15 }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        {
            userId: 9,
            gameId: 15,
            betAmount: 4.50,
            winAmount: 0,
            multiplier: 0,
            status: 'loss',
            betData: JSON.stringify({ lines: 30, coinValue: 0.15 }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        // Small bets - wins
        {
            userId: 2,
            gameId: 3,
            betAmount: 2.00,
            winAmount: 6.00,
            multiplier: 3.00,
            status: 'win',
            betData: JSON.stringify({ lines: 20, coinValue: 0.10 }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        {
            userId: 4,
            gameId: 7,
            betAmount: 5.00,
            winAmount: 12.50,
            multiplier: 2.50,
            status: 'win',
            betData: JSON.stringify({ lines: 25, coinValue: 0.20 }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        {
            userId: 6,
            gameId: 10,
            betAmount: 3.50,
            winAmount: 14.00,
            multiplier: 4.00,
            status: 'win',
            betData: JSON.stringify({ lines: 20, coinValue: 0.175 }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        // Medium bets - losses
        {
            userId: 8,
            gameId: 14,
            betAmount: 15.00,
            winAmount: 0,
            multiplier: 0,
            status: 'loss',
            betData: JSON.stringify({ lines: 30, coinValue: 0.50 }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        {
            userId: 11,
            gameId: 18,
            betAmount: 25.00,
            winAmount: 0,
            multiplier: 0,
            status: 'loss',
            betData: JSON.stringify({ lines: 40, coinValue: 0.625 }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        {
            userId: 13,
            gameId: 20,
            betAmount: 30.00,
            winAmount: 0,
            multiplier: 0,
            status: 'loss',
            betData: JSON.stringify({ lines: 50, coinValue: 0.60 }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        {
            userId: 15,
            gameId: 22,
            betAmount: 20.00,
            winAmount: 0,
            multiplier: 0,
            status: 'loss',
            betData: JSON.stringify({ lines: 25, coinValue: 0.80 }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        // Medium bets - wins
        {
            userId: 12,
            gameId: 19,
            betAmount: 20.00,
            winAmount: 140.00,
            multiplier: 7.00,
            status: 'win',
            betData: JSON.stringify({ lines: 40, coinValue: 0.50 }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        {
            userId: 14,
            gameId: 21,
            betAmount: 35.00,
            winAmount: 280.00,
            multiplier: 8.00,
            status: 'win',
            betData: JSON.stringify({ lines: 50, coinValue: 0.70 }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        // Large bets - losses
        {
            userId: 16,
            gameId: 23,
            betAmount: 75.00,
            winAmount: 0,
            multiplier: 0,
            status: 'loss',
            betData: JSON.stringify({ lines: 50, coinValue: 1.50 }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        {
            userId: 17,
            gameId: 24,
            betAmount: 100.00,
            winAmount: 0,
            multiplier: 0,
            status: 'loss',
            betData: JSON.stringify({ lines: 50, coinValue: 2.00 }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        // Large bets - wins
        {
            userId: 10,
            gameId: 2,
            betAmount: 80.00,
            winAmount: 1600.00,
            multiplier: 20.00,
            status: 'win',
            betData: JSON.stringify({ lines: 40, coinValue: 2.00 }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        {
            userId: 10,
            gameId: 6,
            betAmount: 120.00,
            winAmount: 3000.00,
            multiplier: 25.00,
            status: 'win',
            betData: JSON.stringify({ lines: 50, coinValue: 2.40 }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        // High roller - losses
        {
            userId: 10,
            gameId: 11,
            betAmount: 250.00,
            winAmount: 0,
            multiplier: 0,
            status: 'loss',
            betData: JSON.stringify({ lines: 50, coinValue: 5.00 }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        // High roller - big win
        {
            userId: 10,
            gameId: 16,
            betAmount: 300.00,
            winAmount: 15000.00,
            multiplier: 50.00,
            status: 'win',
            betData: JSON.stringify({ lines: 50, coinValue: 6.00 }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        // Additional slots bets for variety
        {
            userId: 18,
            gameId: 4,
            betAmount: 10.00,
            winAmount: 0,
            multiplier: 0,
            status: 'loss',
            betData: JSON.stringify({ lines: 20, coinValue: 0.50 }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        {
            userId: 19,
            gameId: 9,
            betAmount: 8.00,
            winAmount: 40.00,
            multiplier: 5.00,
            status: 'win',
            betData: JSON.stringify({ lines: 20, coinValue: 0.40 }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        {
            userId: 20,
            gameId: 13,
            betAmount: 12.00,
            winAmount: 0,
            multiplier: 0,
            status: 'loss',
            betData: JSON.stringify({ lines: 30, coinValue: 0.40 }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        {
            userId: 1,
            gameId: 17,
            betAmount: 6.00,
            winAmount: 18.00,
            multiplier: 3.00,
            status: 'win',
            betData: JSON.stringify({ lines: 20, coinValue: 0.30 }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        {
            userId: 3,
            gameId: 25,
            betAmount: 45.00,
            winAmount: 0,
            multiplier: 0,
            status: 'loss',
            betData: JSON.stringify({ lines: 45, coinValue: 1.00 }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },

        // ========== LIVE CASINO BETS (15 bets, gameIds: 26-35) ==========
        // Small bets - losses
        {
            userId: 2,
            gameId: 26,
            betAmount: 5.00,
            winAmount: 0,
            multiplier: 0,
            status: 'loss',
            betData: JSON.stringify({ hand: 'player', cards: ['7', '9'] }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        {
            userId: 4,
            gameId: 27,
            betAmount: 8.00,
            winAmount: 0,
            multiplier: 0,
            status: 'loss',
            betData: JSON.stringify({ betType: 'red', number: 15 }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        {
            userId: 6,
            gameId: 28,
            betAmount: 10.00,
            winAmount: 0,
            multiplier: 0,
            status: 'loss',
            betData: JSON.stringify({ hand: 'banker', cards: ['K', 'Q'] }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        // Small bets - wins
        {
            userId: 5,
            gameId: 29,
            betAmount: 7.50,
            winAmount: 18.75,
            multiplier: 2.50,
            status: 'win',
            betData: JSON.stringify({ hand: 'player', cards: ['A', 'K'] }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        {
            userId: 7,
            gameId: 30,
            betAmount: 6.00,
            winAmount: 12.00,
            multiplier: 2.00,
            status: 'win',
            betData: JSON.stringify({ betType: 'black', number: 26 }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        // Medium bets - losses
        {
            userId: 9,
            gameId: 31,
            betAmount: 25.00,
            winAmount: 0,
            multiplier: 0,
            status: 'loss',
            betData: JSON.stringify({ hand: 'banker', cards: ['9', '7'] }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        {
            userId: 11,
            gameId: 32,
            betAmount: 35.00,
            winAmount: 0,
            multiplier: 0,
            status: 'loss',
            betData: JSON.stringify({ betType: 'even', number: 11 }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        {
            userId: 13,
            gameId: 33,
            betAmount: 40.00,
            winAmount: 0,
            multiplier: 0,
            status: 'loss',
            betData: JSON.stringify({ hand: 'player', cards: ['8', '5'] }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        // Medium bets - wins
        {
            userId: 10,
            gameId: 34,
            betAmount: 50.00,
            winAmount: 175.00,
            multiplier: 3.50,
            status: 'win',
            betData: JSON.stringify({ hand: 'banker', cards: ['A', 'A'] }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        {
            userId: 12,
            gameId: 35,
            betAmount: 30.00,
            winAmount: 1050.00,
            multiplier: 35.00,
            status: 'win',
            betData: JSON.stringify({ betType: 'straight', number: 17 }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        // Large bets - losses
        {
            userId: 14,
            gameId: 26,
            betAmount: 100.00,
            winAmount: 0,
            multiplier: 0,
            status: 'loss',
            betData: JSON.stringify({ hand: 'player', cards: ['10', 'J'] }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        {
            userId: 16,
            gameId: 27,
            betAmount: 80.00,
            winAmount: 0,
            multiplier: 0,
            status: 'loss',
            betData: JSON.stringify({ betType: 'dozen', number: 5 }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        // Large bets - wins
        {
            userId: 10,
            gameId: 28,
            betAmount: 150.00,
            winAmount: 375.00,
            multiplier: 2.50,
            status: 'win',
            betData: JSON.stringify({ hand: 'banker', cards: ['K', 'K'] }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        // Pending bet
        {
            userId: 17,
            gameId: 29,
            betAmount: 20.00,
            winAmount: 0,
            multiplier: 0,
            status: 'pending',
            betData: JSON.stringify({ hand: 'player', cards: [] }),
            createdAt: new Date().toISOString(),
            settledAt: null,
        },
        {
            userId: 18,
            gameId: 30,
            betAmount: 15.00,
            winAmount: 0,
            multiplier: 0,
            status: 'pending',
            betData: JSON.stringify({ betType: 'red', number: null }),
            createdAt: new Date().toISOString(),
            settledAt: null,
        },

        // ========== CRASH BETS (20 bets, gameIds: 36-43) ==========
        // Small bets - losses
        {
            userId: 1,
            gameId: 36,
            betAmount: 2.00,
            winAmount: 0,
            multiplier: 0,
            status: 'loss',
            betData: JSON.stringify({ crashPoint: 1.52, cashoutPoint: null }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        {
            userId: 3,
            gameId: 37,
            betAmount: 3.50,
            winAmount: 0,
            multiplier: 0,
            status: 'loss',
            betData: JSON.stringify({ crashPoint: 1.08, cashoutPoint: null }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        {
            userId: 5,
            gameId: 38,
            betAmount: 5.00,
            winAmount: 0,
            multiplier: 0,
            status: 'loss',
            betData: JSON.stringify({ crashPoint: 1.23, cashoutPoint: null }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        {
            userId: 7,
            gameId: 39,
            betAmount: 4.00,
            winAmount: 0,
            multiplier: 0,
            status: 'loss',
            betData: JSON.stringify({ crashPoint: 1.45, cashoutPoint: null }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        // Small bets - wins
        {
            userId: 2,
            gameId: 40,
            betAmount: 3.00,
            winAmount: 6.00,
            multiplier: 2.00,
            status: 'win',
            betData: JSON.stringify({ crashPoint: 3.45, cashoutPoint: 2.00 }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        {
            userId: 4,
            gameId: 41,
            betAmount: 6.00,
            winAmount: 12.00,
            multiplier: 2.00,
            status: 'win',
            betData: JSON.stringify({ crashPoint: 5.67, cashoutPoint: 2.00 }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        {
            userId: 6,
            gameId: 42,
            betAmount: 5.50,
            winAmount: 13.75,
            multiplier: 2.50,
            status: 'win',
            betData: JSON.stringify({ crashPoint: 4.23, cashoutPoint: 2.50 }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        {
            userId: 8,
            gameId: 43,
            betAmount: 7.00,
            winAmount: 21.00,
            multiplier: 3.00,
            status: 'win',
            betData: JSON.stringify({ crashPoint: 6.78, cashoutPoint: 3.00 }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        // Medium bets - losses
        {
            userId: 9,
            gameId: 36,
            betAmount: 20.00,
            winAmount: 0,
            multiplier: 0,
            status: 'loss',
            betData: JSON.stringify({ crashPoint: 1.89, cashoutPoint: null }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        {
            userId: 11,
            gameId: 37,
            betAmount: 25.00,
            winAmount: 0,
            multiplier: 0,
            status: 'loss',
            betData: JSON.stringify({ crashPoint: 1.34, cashoutPoint: null }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        {
            userId: 13,
            gameId: 38,
            betAmount: 30.00,
            winAmount: 0,
            multiplier: 0,
            status: 'loss',
            betData: JSON.stringify({ crashPoint: 1.67, cashoutPoint: null }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        // Medium bets - wins
        {
            userId: 12,
            gameId: 39,
            betAmount: 35.00,
            winAmount: 140.00,
            multiplier: 4.00,
            status: 'win',
            betData: JSON.stringify({ crashPoint: 8.92, cashoutPoint: 4.00 }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        {
            userId: 14,
            gameId: 40,
            betAmount: 40.00,
            winAmount: 200.00,
            multiplier: 5.00,
            status: 'win',
            betData: JSON.stringify({ crashPoint: 12.45, cashoutPoint: 5.00 }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        // Large bets - losses
        {
            userId: 15,
            gameId: 41,
            betAmount: 75.00,
            winAmount: 0,
            multiplier: 0,
            status: 'loss',
            betData: JSON.stringify({ crashPoint: 1.56, cashoutPoint: null }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        {
            userId: 16,
            gameId: 42,
            betAmount: 100.00,
            winAmount: 0,
            multiplier: 0,
            status: 'loss',
            betData: JSON.stringify({ crashPoint: 1.12, cashoutPoint: null }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        // Large bets - big wins
        {
            userId: 10,
            gameId: 43,
            betAmount: 120.00,
            winAmount: 1200.00,
            multiplier: 10.00,
            status: 'win',
            betData: JSON.stringify({ crashPoint: 15.67, cashoutPoint: 10.00 }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        {
            userId: 10,
            gameId: 36,
            betAmount: 150.00,
            winAmount: 3000.00,
            multiplier: 20.00,
            status: 'win',
            betData: JSON.stringify({ crashPoint: 34.56, cashoutPoint: 20.00 }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        // High roller - huge win
        {
            userId: 10,
            gameId: 37,
            betAmount: 200.00,
            winAmount: 10000.00,
            multiplier: 50.00,
            status: 'win',
            betData: JSON.stringify({ crashPoint: 89.23, cashoutPoint: 50.00 }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        // Pending crash bet
        {
            userId: 19,
            gameId: 38,
            betAmount: 10.00,
            winAmount: 0,
            multiplier: 0,
            status: 'pending',
            betData: JSON.stringify({ crashPoint: null, cashoutPoint: null }),
            createdAt: new Date().toISOString(),
            settledAt: null,
        },
        {
            userId: 17,
            gameId: 39,
            betAmount: 15.00,
            winAmount: 0,
            multiplier: 0,
            status: 'loss',
            betData: JSON.stringify({ crashPoint: 1.78, cashoutPoint: null }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },

        // ========== TABLE GAMES BETS (10 bets, gameIds: 44-51) ==========
        // Small bets - losses
        {
            userId: 2,
            gameId: 44,
            betAmount: 5.00,
            winAmount: 0,
            multiplier: 0,
            status: 'loss',
            betData: JSON.stringify({ hand: 'player', cards: ['10', 'Q'], dealerCards: ['A', 'K'] }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        {
            userId: 4,
            gameId: 45,
            betAmount: 8.00,
            winAmount: 0,
            multiplier: 0,
            status: 'loss',
            betData: JSON.stringify({ hand: 'player', cards: ['7', '9'], dealerCards: ['10', 'J'] }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        // Small bets - wins
        {
            userId: 3,
            gameId: 46,
            betAmount: 10.00,
            winAmount: 25.00,
            multiplier: 2.50,
            status: 'win',
            betData: JSON.stringify({ hand: 'player', cards: ['A', 'K'], dealerCards: ['10', '6'] }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        {
            userId: 5,
            gameId: 47,
            betAmount: 7.50,
            winAmount: 15.00,
            multiplier: 2.00,
            status: 'win',
            betData: JSON.stringify({ hand: 'player', cards: ['9', '10'], dealerCards: ['8', '9'] }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        // Medium bets - losses
        {
            userId: 7,
            gameId: 48,
            betAmount: 25.00,
            winAmount: 0,
            multiplier: 0,
            status: 'loss',
            betData: JSON.stringify({ hand: 'player', cards: ['8', '8'], dealerCards: ['10', 'A'] }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        {
            userId: 9,
            gameId: 49,
            betAmount: 35.00,
            winAmount: 0,
            multiplier: 0,
            status: 'loss',
            betData: JSON.stringify({ hand: 'player', cards: ['J', 'Q'], dealerCards: ['A', 'A'] }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        // Medium bets - wins
        {
            userId: 10,
            gameId: 50,
            betAmount: 50.00,
            winAmount: 125.00,
            multiplier: 2.50,
            status: 'win',
            betData: JSON.stringify({ hand: 'player', cards: ['A', 'A'], dealerCards: ['K', '5'] }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        // Large bets - losses
        {
            userId: 11,
            gameId: 51,
            betAmount: 80.00,
            winAmount: 0,
            multiplier: 0,
            status: 'loss',
            betData: JSON.stringify({ hand: 'player', cards: ['10', 'J'], dealerCards: ['A', 'Q'] }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        // Large bets - wins
        {
            userId: 10,
            gameId: 44,
            betAmount: 100.00,
            winAmount: 250.00,
            multiplier: 2.50,
            status: 'win',
            betData: JSON.stringify({ hand: 'player', cards: ['A', 'K'], dealerCards: ['9', '10'] }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        // Pending table game bet
        {
            userId: 13,
            gameId: 45,
            betAmount: 20.00,
            winAmount: 0,
            multiplier: 0,
            status: 'pending',
            betData: JSON.stringify({ hand: 'player', cards: [], dealerCards: [] }),
            createdAt: new Date().toISOString(),
            settledAt: null,
        },

        // ========== FISHING GAMES BETS (7 bets, gameIds: 52-56) ==========
        // Small bets - losses
        {
            userId: 1,
            gameId: 52,
            betAmount: 2.50,
            winAmount: 0,
            multiplier: 0,
            status: 'loss',
            betData: JSON.stringify({ shots: 15, fishCaught: 0 }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        {
            userId: 3,
            gameId: 53,
            betAmount: 5.00,
            winAmount: 0,
            multiplier: 0,
            status: 'loss',
            betData: JSON.stringify({ shots: 20, fishCaught: 0 }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        // Small bets - wins
        {
            userId: 2,
            gameId: 54,
            betAmount: 3.00,
            winAmount: 9.00,
            multiplier: 3.00,
            status: 'win',
            betData: JSON.stringify({ shots: 10, fishCaught: 3 }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        {
            userId: 4,
            gameId: 55,
            betAmount: 7.50,
            winAmount: 22.50,
            multiplier: 3.00,
            status: 'win',
            betData: JSON.stringify({ shots: 15, fishCaught: 5 }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        // Medium bets - losses
        {
            userId: 6,
            gameId: 56,
            betAmount: 20.00,
            winAmount: 0,
            multiplier: 0,
            status: 'loss',
            betData: JSON.stringify({ shots: 30, fishCaught: 0 }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        // Medium bets - wins
        {
            userId: 8,
            gameId: 52,
            betAmount: 30.00,
            winAmount: 150.00,
            multiplier: 5.00,
            status: 'win',
            betData: JSON.stringify({ shots: 25, fishCaught: 8 }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        // Large bets - big win
        {
            userId: 10,
            gameId: 53,
            betAmount: 100.00,
            winAmount: 1000.00,
            multiplier: 10.00,
            status: 'win',
            betData: JSON.stringify({ shots: 40, fishCaught: 15 }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },

        // ========== ARCADE GAMES BETS (3 bets, gameIds: 57-60) ==========
        // Small bet - loss
        {
            userId: 5,
            gameId: 57,
            betAmount: 4.00,
            winAmount: 0,
            multiplier: 0,
            status: 'loss',
            betData: JSON.stringify({ level: 3, score: 1250 }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        // Medium bet - win
        {
            userId: 7,
            gameId: 58,
            betAmount: 15.00,
            winAmount: 45.00,
            multiplier: 3.00,
            status: 'win',
            betData: JSON.stringify({ level: 7, score: 5680 }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
        // Large bet - big win
        {
            userId: 10,
            gameId: 59,
            betAmount: 75.00,
            winAmount: 750.00,
            multiplier: 10.00,
            status: 'win',
            betData: JSON.stringify({ level: 12, score: 15240 }),
            createdAt: getCreatedDate().toISOString(),
            settledAt: getCreatedDate().toISOString(),
        },
    ];

    await db.insert(bets).values(sampleBets);
    
    console.log('✅ Bets seeder completed successfully - 80 bets created');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});