import { db } from '@/db';
import { games } from '@/db/schema';

async function main() {
    const sampleGames = [
        // Slots (categoryId: 1) - 25 games
        {
            name: 'Sweet Bonanza',
            slug: 'sweet-bonanza',
            categoryId: 1,
            provider: 'Pragmatic Play',
            imageUrl: '/games/sweet-bonanza.jpg',
            thumbnailUrl: '/games/thumbs/sweet-bonanza.jpg',
            description: 'Colorful candy-themed slot with tumbling reels and multipliers',
            minBet: 0.20,
            maxBet: 500.00,
            rtp: 96.51,
            isFeatured: true,
            isActive: true,
            playCount: 45230,
            createdAt: new Date('2024-08-15').toISOString(),
            updatedAt: new Date('2024-08-15').toISOString(),
        },
        {
            name: 'Gates of Olympus',
            slug: 'gates-of-olympus',
            categoryId: 1,
            provider: 'Pragmatic Play',
            imageUrl: '/games/gates-of-olympus.jpg',
            thumbnailUrl: '/games/thumbs/gates-of-olympus.jpg',
            description: 'Greek mythology themed slot with Zeus and cascading wins',
            minBet: 0.20,
            maxBet: 500.00,
            rtp: 96.50,
            isFeatured: true,
            isActive: true,
            playCount: 48750,
            createdAt: new Date('2024-08-20').toISOString(),
            updatedAt: new Date('2024-08-20').toISOString(),
        },
        {
            name: 'Sugar Rush',
            slug: 'sugar-rush',
            categoryId: 1,
            provider: 'Pragmatic Play',
            imageUrl: '/games/sugar-rush.jpg',
            thumbnailUrl: '/games/thumbs/sugar-rush.jpg',
            description: 'Sweet candy adventure with cluster pays and multipliers',
            minBet: 0.20,
            maxBet: 400.00,
            rtp: 96.50,
            isFeatured: false,
            isActive: true,
            playCount: 32100,
            createdAt: new Date('2024-09-01').toISOString(),
            updatedAt: new Date('2024-09-01').toISOString(),
        },
        {
            name: 'Wild West Gold',
            slug: 'wild-west-gold',
            categoryId: 1,
            provider: 'Pragmatic Play',
            imageUrl: '/games/wild-west-gold.jpg',
            thumbnailUrl: '/games/thumbs/wild-west-gold.jpg',
            description: 'Wild West adventure with sticky wilds and free spins',
            minBet: 0.20,
            maxBet: 250.00,
            rtp: 96.51,
            isFeatured: false,
            isActive: true,
            playCount: 28450,
            createdAt: new Date('2024-09-05').toISOString(),
            updatedAt: new Date('2024-09-05').toISOString(),
        },
        {
            name: 'Book of Dead',
            slug: 'book-of-dead',
            categoryId: 1,
            provider: "Play'n GO",
            imageUrl: '/games/book-of-dead.jpg',
            thumbnailUrl: '/games/thumbs/book-of-dead.jpg',
            description: 'Egyptian adventure with expanding symbols and free spins',
            minBet: 0.10,
            maxBet: 200.00,
            rtp: 96.21,
            isFeatured: false,
            isActive: true,
            playCount: 42800,
            createdAt: new Date('2024-09-10').toISOString(),
            updatedAt: new Date('2024-09-10').toISOString(),
        },
        {
            name: 'Starburst',
            slug: 'starburst',
            categoryId: 1,
            provider: 'NetEnt',
            imageUrl: '/games/starburst.jpg',
            thumbnailUrl: '/games/thumbs/starburst.jpg',
            description: 'Classic space-themed slot with expanding wilds',
            minBet: 0.10,
            maxBet: 100.00,
            rtp: 96.09,
            isFeatured: false,
            isActive: true,
            playCount: 39200,
            createdAt: new Date('2024-09-15').toISOString(),
            updatedAt: new Date('2024-09-15').toISOString(),
        },
        {
            name: "Gonzo's Quest",
            slug: 'gonzos-quest',
            categoryId: 1,
            provider: 'NetEnt',
            imageUrl: '/games/gonzos-quest.jpg',
            thumbnailUrl: '/games/thumbs/gonzos-quest.jpg',
            description: 'Adventure with Gonzo featuring avalanche reels and multipliers',
            minBet: 0.20,
            maxBet: 150.00,
            rtp: 95.97,
            isFeatured: false,
            isActive: true,
            playCount: 35600,
            createdAt: new Date('2024-09-20').toISOString(),
            updatedAt: new Date('2024-09-20').toISOString(),
        },
        {
            name: 'Mega Moolah',
            slug: 'mega-moolah',
            categoryId: 1,
            provider: 'Microgaming',
            imageUrl: '/games/mega-moolah.jpg',
            thumbnailUrl: '/games/thumbs/mega-moolah.jpg',
            description: 'Safari-themed progressive jackpot slot with huge wins',
            minBet: 0.25,
            maxBet: 125.00,
            rtp: 88.12,
            isFeatured: true,
            isActive: true,
            playCount: 50000,
            createdAt: new Date('2024-09-25').toISOString(),
            updatedAt: new Date('2024-09-25').toISOString(),
        },
        {
            name: 'Vikings Go Berzerk',
            slug: 'vikings-go-berzerk',
            categoryId: 1,
            provider: 'Yggdrasil',
            imageUrl: '/games/vikings-go-berzerk.jpg',
            thumbnailUrl: '/games/thumbs/vikings-go-berzerk.jpg',
            description: 'Norse warriors battle with sticky wilds and free spins',
            minBet: 0.10,
            maxBet: 200.00,
            rtp: 96.10,
            isFeatured: false,
            isActive: true,
            playCount: 24300,
            createdAt: new Date('2024-10-01').toISOString(),
            updatedAt: new Date('2024-10-01').toISOString(),
        },
        {
            name: 'Book of Shadows',
            slug: 'book-of-shadows',
            categoryId: 1,
            provider: 'Nolimit City',
            imageUrl: '/games/book-of-shadows.jpg',
            thumbnailUrl: '/games/thumbs/book-of-shadows.jpg',
            description: 'Dark mystery adventure with expanding symbols',
            minBet: 0.20,
            maxBet: 100.00,
            rtp: 96.07,
            isFeatured: false,
            isActive: true,
            playCount: 18750,
            createdAt: new Date('2024-10-05').toISOString(),
            updatedAt: new Date('2024-10-05').toISOString(),
        },
        {
            name: 'Razor Shark',
            slug: 'razor-shark',
            categoryId: 1,
            provider: 'Push Gaming',
            imageUrl: '/games/razor-shark.jpg',
            thumbnailUrl: '/games/thumbs/razor-shark.jpg',
            description: 'Underwater adventure with mystery stacks and free spins',
            minBet: 0.10,
            maxBet: 100.00,
            rtp: 96.70,
            isFeatured: false,
            isActive: true,
            playCount: 27800,
            createdAt: new Date('2024-10-10').toISOString(),
            updatedAt: new Date('2024-10-10').toISOString(),
        },
        {
            name: 'Wanted Dead or a Wild',
            slug: 'wanted-dead-or-a-wild',
            categoryId: 1,
            provider: 'Hacksaw Gaming',
            imageUrl: '/games/wanted-dead-or-a-wild.jpg',
            thumbnailUrl: '/games/thumbs/wanted-dead-or-a-wild.jpg',
            description: 'Wild West bounty hunt with expanding wilds',
            minBet: 0.10,
            maxBet: 100.00,
            rtp: 96.38,
            isFeatured: false,
            isActive: true,
            playCount: 31200,
            createdAt: new Date('2024-10-15').toISOString(),
            updatedAt: new Date('2024-10-15').toISOString(),
        },
        {
            name: 'The Dog House',
            slug: 'the-dog-house',
            categoryId: 1,
            provider: 'Pragmatic Play',
            imageUrl: '/games/the-dog-house.jpg',
            thumbnailUrl: '/games/thumbs/the-dog-house.jpg',
            description: 'Fun canine adventure with sticky wilds and multipliers',
            minBet: 0.20,
            maxBet: 250.00,
            rtp: 96.51,
            isFeatured: false,
            isActive: true,
            playCount: 29400,
            createdAt: new Date('2024-10-20').toISOString(),
            updatedAt: new Date('2024-10-20').toISOString(),
        },
        {
            name: 'Fruit Party',
            slug: 'fruit-party',
            categoryId: 1,
            provider: 'Pragmatic Play',
            imageUrl: '/games/fruit-party.jpg',
            thumbnailUrl: '/games/thumbs/fruit-party.jpg',
            description: 'Fruity celebration with cluster pays and multipliers',
            minBet: 0.20,
            maxBet: 500.00,
            rtp: 96.50,
            isFeatured: false,
            isActive: true,
            playCount: 33650,
            createdAt: new Date('2024-10-25').toISOString(),
            updatedAt: new Date('2024-10-25').toISOString(),
        },
        {
            name: 'Big Bass Bonanza',
            slug: 'big-bass-bonanza',
            categoryId: 1,
            provider: 'Pragmatic Play',
            imageUrl: '/games/big-bass-bonanza.jpg',
            thumbnailUrl: '/games/thumbs/big-bass-bonanza.jpg',
            description: 'Fishing adventure with money collect and free spins',
            minBet: 0.10,
            maxBet: 250.00,
            rtp: 96.71,
            isFeatured: true,
            isActive: true,
            playCount: 46800,
            createdAt: new Date('2024-11-01').toISOString(),
            updatedAt: new Date('2024-11-01').toISOString(),
        },
        {
            name: 'Mystery Joker',
            slug: 'mystery-joker',
            categoryId: 1,
            provider: "Play'n GO",
            imageUrl: '/games/mystery-joker.jpg',
            thumbnailUrl: '/games/thumbs/mystery-joker.jpg',
            description: 'Classic fruit machine with mystery wheel bonus',
            minBet: 0.10,
            maxBet: 100.00,
            rtp: 96.98,
            isFeatured: false,
            isActive: true,
            playCount: 19200,
            createdAt: new Date('2024-11-05').toISOString(),
            updatedAt: new Date('2024-11-05').toISOString(),
        },
        {
            name: 'Dead or Alive 2',
            slug: 'dead-or-alive-2',
            categoryId: 1,
            provider: 'NetEnt',
            imageUrl: '/games/dead-or-alive-2.jpg',
            thumbnailUrl: '/games/thumbs/dead-or-alive-2.jpg',
            description: 'Wild West showdown with sticky wilds and huge wins',
            minBet: 0.09,
            maxBet: 90.00,
            rtp: 96.80,
            isFeatured: false,
            isActive: true,
            playCount: 36400,
            createdAt: new Date('2024-11-10').toISOString(),
            updatedAt: new Date('2024-11-10').toISOString(),
        },
        {
            name: 'Bonanza Megaways',
            slug: 'bonanza-megaways',
            categoryId: 1,
            provider: 'BTG',
            imageUrl: '/games/bonanza-megaways.jpg',
            thumbnailUrl: '/games/thumbs/bonanza-megaways.jpg',
            description: 'Mining adventure with megaways and unlimited multipliers',
            minBet: 0.20,
            maxBet: 40.00,
            rtp: 96.00,
            isFeatured: false,
            isActive: true,
            playCount: 41200,
            createdAt: new Date('2024-11-15').toISOString(),
            updatedAt: new Date('2024-11-15').toISOString(),
        },
        {
            name: 'Rainbow Riches',
            slug: 'rainbow-riches',
            categoryId: 1,
            provider: 'JILI',
            imageUrl: '/games/rainbow-riches.jpg',
            thumbnailUrl: '/games/thumbs/rainbow-riches.jpg',
            description: 'Irish luck with leprechauns and pots of gold',
            minBet: 0.10,
            maxBet: 200.00,
            rtp: 96.50,
            isFeatured: false,
            isActive: true,
            playCount: 25600,
            createdAt: new Date('2024-11-20').toISOString(),
            updatedAt: new Date('2024-11-20').toISOString(),
        },
        {
            name: 'Money Train 3',
            slug: 'money-train-3',
            categoryId: 1,
            provider: 'Nolimit City',
            imageUrl: '/games/money-train-3.jpg',
            thumbnailUrl: '/games/thumbs/money-train-3.jpg',
            description: 'High-speed train robbery with persistent symbols',
            minBet: 0.10,
            maxBet: 20.00,
            rtp: 96.10,
            isFeatured: false,
            isActive: true,
            playCount: 38900,
            createdAt: new Date('2024-11-25').toISOString(),
            updatedAt: new Date('2024-11-25').toISOString(),
        },
        {
            name: "Jammin' Jars",
            slug: 'jammin-jars',
            categoryId: 1,
            provider: 'Push Gaming',
            imageUrl: '/games/jammin-jars.jpg',
            thumbnailUrl: '/games/thumbs/jammin-jars.jpg',
            description: 'Funky disco fruits with cluster pays and rainbow feature',
            minBet: 0.20,
            maxBet: 100.00,
            rtp: 96.83,
            isFeatured: false,
            isActive: true,
            playCount: 30700,
            createdAt: new Date('2024-12-01').toISOString(),
            updatedAt: new Date('2024-12-01').toISOString(),
        },
        {
            name: "Stack 'Em",
            slug: 'stack-em',
            categoryId: 1,
            provider: 'Hacksaw Gaming',
            imageUrl: '/games/stack-em.jpg',
            thumbnailUrl: '/games/thumbs/stack-em.jpg',
            description: 'Stack symbols high for massive multiplier wins',
            minBet: 0.20,
            maxBet: 100.00,
            rtp: 96.26,
            isFeatured: false,
            isActive: true,
            playCount: 21800,
            createdAt: new Date('2024-12-05').toISOString(),
            updatedAt: new Date('2024-12-05').toISOString(),
        },
        {
            name: '5 Lions Megaways',
            slug: '5-lions-megaways',
            categoryId: 1,
            provider: 'Pragmatic Play',
            imageUrl: '/games/5-lions-megaways.jpg',
            thumbnailUrl: '/games/thumbs/5-lions-megaways.jpg',
            description: 'Asian-themed megaways with expanding reels',
            minBet: 0.20,
            maxBet: 500.00,
            rtp: 96.50,
            isFeatured: false,
            isActive: true,
            playCount: 26900,
            createdAt: new Date('2024-12-10').toISOString(),
            updatedAt: new Date('2024-12-10').toISOString(),
        },
        {
            name: 'Reactoonz',
            slug: 'reactoonz',
            categoryId: 1,
            provider: "Play'n GO",
            imageUrl: '/games/reactoonz.jpg',
            thumbnailUrl: '/games/thumbs/reactoonz.jpg',
            description: 'Alien creatures with cascading wins and quantum features',
            minBet: 0.20,
            maxBet: 100.00,
            rtp: 96.51,
            isFeatured: false,
            isActive: true,
            playCount: 28300,
            createdAt: new Date('2024-12-15').toISOString(),
            updatedAt: new Date('2024-12-15').toISOString(),
        },
        {
            name: 'Twin Spin',
            slug: 'twin-spin',
            categoryId: 1,
            provider: 'NetEnt',
            imageUrl: '/games/twin-spin.jpg',
            thumbnailUrl: '/games/thumbs/twin-spin.jpg',
            description: 'Retro slot with twin reel feature on every spin',
            minBet: 0.25,
            maxBet: 125.00,
            rtp: 96.55,
            isFeatured: false,
            isActive: true,
            playCount: 23400,
            createdAt: new Date('2024-12-20').toISOString(),
            updatedAt: new Date('2024-12-20').toISOString(),
        },

        // Live Casino (categoryId: 2) - 10 games
        {
            name: 'Lightning Roulette',
            slug: 'lightning-roulette',
            categoryId: 2,
            provider: 'Evolution Gaming',
            imageUrl: '/games/lightning-roulette.jpg',
            thumbnailUrl: '/games/thumbs/lightning-roulette.jpg',
            description: 'Enhanced roulette with random lightning multipliers up to 500x',
            minBet: 0.20,
            maxBet: 10000.00,
            rtp: 97.30,
            isFeatured: true,
            isActive: true,
            playCount: 47500,
            createdAt: new Date('2024-08-18').toISOString(),
            updatedAt: new Date('2024-08-18').toISOString(),
        },
        {
            name: 'Crazy Time',
            slug: 'crazy-time',
            categoryId: 2,
            provider: 'Evolution Gaming',
            imageUrl: '/games/crazy-time.jpg',
            thumbnailUrl: '/games/thumbs/crazy-time.jpg',
            description: 'Ultimate game show with four exciting bonus games',
            minBet: 0.10,
            maxBet: 5000.00,
            rtp: 95.41,
            isFeatured: true,
            isActive: true,
            playCount: 49800,
            createdAt: new Date('2024-08-22').toISOString(),
            updatedAt: new Date('2024-08-22').toISOString(),
        },
        {
            name: 'Mega Ball',
            slug: 'mega-ball',
            categoryId: 2,
            provider: 'Evolution Gaming',
            imageUrl: '/games/mega-ball.jpg',
            thumbnailUrl: '/games/thumbs/mega-ball.jpg',
            description: 'Live bingo with multiplier balls for massive wins',
            minBet: 0.10,
            maxBet: 1000.00,
            rtp: 95.40,
            isFeatured: false,
            isActive: true,
            playCount: 31500,
            createdAt: new Date('2024-09-03').toISOString(),
            updatedAt: new Date('2024-09-03').toISOString(),
        },
        {
            name: 'Dream Catcher',
            slug: 'dream-catcher',
            categoryId: 2,
            provider: 'Evolution Gaming',
            imageUrl: '/games/dream-catcher.jpg',
            thumbnailUrl: '/games/thumbs/dream-catcher.jpg',
            description: 'Money wheel game with multipliers and bonuses',
            minBet: 0.10,
            maxBet: 2500.00,
            rtp: 96.58,
            isFeatured: false,
            isActive: true,
            playCount: 28700,
            createdAt: new Date('2024-09-12').toISOString(),
            updatedAt: new Date('2024-09-12').toISOString(),
        },
        {
            name: 'Monopoly Live',
            slug: 'monopoly-live',
            categoryId: 2,
            provider: 'Evolution Gaming',
            imageUrl: '/games/monopoly-live.jpg',
            thumbnailUrl: '/games/thumbs/monopoly-live.jpg',
            description: 'Monopoly board game with Mr. Monopoly and 3D bonus',
            minBet: 0.10,
            maxBet: 5000.00,
            rtp: 96.23,
            isFeatured: false,
            isActive: true,
            playCount: 39200,
            createdAt: new Date('2024-09-22').toISOString(),
            updatedAt: new Date('2024-09-22').toISOString(),
        },
        {
            name: 'Deal or No Deal',
            slug: 'deal-or-no-deal',
            categoryId: 2,
            provider: 'Evolution Gaming',
            imageUrl: '/games/deal-or-no-deal.jpg',
            thumbnailUrl: '/games/thumbs/deal-or-no-deal.jpg',
            description: 'TV show inspired game with briefcase selections',
            minBet: 0.10,
            maxBet: 2000.00,
            rtp: 95.42,
            isFeatured: false,
            isActive: true,
            playCount: 26400,
            createdAt: new Date('2024-10-03').toISOString(),
            updatedAt: new Date('2024-10-03').toISOString(),
        },
        {
            name: 'Lightning Dice',
            slug: 'lightning-dice',
            categoryId: 2,
            provider: 'Evolution Gaming',
            imageUrl: '/games/lightning-dice.jpg',
            thumbnailUrl: '/games/thumbs/lightning-dice.jpg',
            description: 'Three dice with lightning multipliers up to 1000x',
            minBet: 0.10,
            maxBet: 5000.00,
            rtp: 96.20,
            isFeatured: false,
            isActive: true,
            playCount: 22800,
            createdAt: new Date('2024-10-18').toISOString(),
            updatedAt: new Date('2024-10-18').toISOString(),
        },
        {
            name: 'Football Studio',
            slug: 'football-studio',
            categoryId: 2,
            provider: 'Evolution Gaming',
            imageUrl: '/games/football-studio.jpg',
            thumbnailUrl: '/games/thumbs/football-studio.jpg',
            description: 'Football-themed card game with simple rules',
            minBet: 0.50,
            maxBet: 5000.00,
            rtp: 96.27,
            isFeatured: false,
            isActive: true,
            playCount: 19600,
            createdAt: new Date('2024-11-02').toISOString(),
            updatedAt: new Date('2024-11-02').toISOString(),
        },
        {
            name: 'Infinite Blackjack',
            slug: 'infinite-blackjack',
            categoryId: 2,
            provider: 'Evolution Gaming',
            imageUrl: '/games/infinite-blackjack.jpg',
            thumbnailUrl: '/games/thumbs/infinite-blackjack.jpg',
            description: 'Unlimited seats blackjack with optional side bets',
            minBet: 1.00,
            maxBet: 5000.00,
            rtp: 99.47,
            isFeatured: false,
            isActive: true,
            playCount: 34200,
            createdAt: new Date('2024-11-12').toISOString(),
            updatedAt: new Date('2024-11-12').toISOString(),
        },
        {
            name: 'Speed Baccarat',
            slug: 'speed-baccarat',
            categoryId: 2,
            provider: 'Evolution Gaming',
            imageUrl: '/games/speed-baccarat.jpg',
            thumbnailUrl: '/games/thumbs/speed-baccarat.jpg',
            description: 'Fast-paced baccarat with 27-second rounds',
            minBet: 1.00,
            maxBet: 10000.00,
            rtp: 98.94,
            isFeatured: false,
            isActive: true,
            playCount: 37800,
            createdAt: new Date('2024-11-28').toISOString(),
            updatedAt: new Date('2024-11-28').toISOString(),
        },

        // Crash Games (categoryId: 4) - 8 games
        {
            name: 'Aviator',
            slug: 'aviator',
            categoryId: 4,
            provider: 'Spribe',
            imageUrl: '/games/aviator.jpg',
            thumbnailUrl: '/games/thumbs/aviator.jpg',
            description: 'Popular crash game with flying plane and instant cashouts',
            minBet: 0.10,
            maxBet: 100.00,
            rtp: 97.00,
            isFeatured: true,
            isActive: true,
            playCount: 48900,
            createdAt: new Date('2024-08-25').toISOString(),
            updatedAt: new Date('2024-08-25').toISOString(),
        },
        {
            name: 'JetX',
            slug: 'jetx',
            categoryId: 4,
            provider: 'SmartSoft',
            imageUrl: '/games/jetx.jpg',
            thumbnailUrl: '/games/thumbs/jetx.jpg',
            description: 'Rocket-themed crash game with multiplier trails',
            minBet: 0.10,
            maxBet: 300.00,
            rtp: 97.00,
            isFeatured: false,
            isActive: true,
            playCount: 41300,
            createdAt: new Date('2024-09-08').toISOString(),
            updatedAt: new Date('2024-09-08').toISOString(),
        },
        {
            name: 'Spaceman',
            slug: 'spaceman',
            categoryId: 4,
            provider: 'Pragmatic Play',
            imageUrl: '/games/spaceman.jpg',
            thumbnailUrl: '/games/thumbs/spaceman.jpg',
            description: 'Astronaut adventure crash game with increasing multipliers',
            minBet: 0.50,
            maxBet: 500.00,
            rtp: 96.50,
            isFeatured: false,
            isActive: true,
            playCount: 36700,
            createdAt: new Date('2024-09-18').toISOString(),
            updatedAt: new Date('2024-09-18').toISOString(),
        },
        {
            name: 'Crash X',
            slug: 'crash-x',
            categoryId: 4,
            provider: 'JILI',
            imageUrl: '/games/crash-x.jpg',
            thumbnailUrl: '/games/thumbs/crash-x.jpg',
            description: 'High-speed crash game with auto cashout options',
            minBet: 0.10,
            maxBet: 200.00,
            rtp: 96.00,
            isFeatured: false,
            isActive: true,
            playCount: 28900,
            createdAt: new Date('2024-10-08').toISOString(),
            updatedAt: new Date('2024-10-08').toISOString(),
        },
        {
            name: 'Mines',
            slug: 'mines',
            categoryId: 4,
            provider: 'Spribe',
            imageUrl: '/games/mines.jpg',
            thumbnailUrl: '/games/thumbs/mines.jpg',
            description: 'Minesweeper-style game with increasing multipliers',
            minBet: 0.10,
            maxBet: 100.00,
            rtp: 97.00,
            isFeatured: false,
            isActive: true,
            playCount: 32400,
            createdAt: new Date('2024-10-22').toISOString(),
            updatedAt: new Date('2024-10-22').toISOString(),
        },
        {
            name: 'Plinko',
            slug: 'plinko',
            categoryId: 4,
            provider: 'Spribe',
            imageUrl: '/games/plinko.jpg',
            thumbnailUrl: '/games/thumbs/plinko.jpg',
            description: 'Drop balls through pegs for random multipliers',
            minBet: 0.10,
            maxBet: 100.00,
            rtp: 97.00,
            isFeatured: false,
            isActive: true,
            playCount: 29800,
            createdAt: new Date('2024-11-08').toISOString(),
            updatedAt: new Date('2024-11-08').toISOString(),
        },
        {
            name: 'Dice',
            slug: 'dice',
            categoryId: 4,
            provider: 'Spribe',
            imageUrl: '/games/dice.jpg',
            thumbnailUrl: '/games/thumbs/dice.jpg',
            description: 'Roll dice and predict outcomes for big wins',
            minBet: 0.10,
            maxBet: 100.00,
            rtp: 99.00,
            isFeatured: false,
            isActive: true,
            playCount: 24600,
            createdAt: new Date('2024-11-18').toISOString(),
            updatedAt: new Date('2024-11-18').toISOString(),
        },
        {
            name: 'Goal',
            slug: 'goal',
            categoryId: 4,
            provider: 'Spribe',
            imageUrl: '/games/goal.jpg',
            thumbnailUrl: '/games/thumbs/goal.jpg',
            description: 'Football-themed penalty shootout with multipliers',
            minBet: 0.10,
            maxBet: 100.00,
            rtp: 97.00,
            isFeatured: false,
            isActive: true,
            playCount: 21700,
            createdAt: new Date('2024-12-03').toISOString(),
            updatedAt: new Date('2024-12-03').toISOString(),
        },

        // Table Games (categoryId: 5) - 8 games
        {
            name: 'Blackjack Classic',
            slug: 'blackjack-classic',
            categoryId: 5,
            provider: 'NetEnt',
            imageUrl: '/games/blackjack-classic.jpg',
            thumbnailUrl: '/games/thumbs/blackjack-classic.jpg',
            description: 'Traditional blackjack with optimal RTP',
            minBet: 1.00,
            maxBet: 500.00,
            rtp: 99.50,
            isFeatured: false,
            isActive: true,
            playCount: 18400,
            createdAt: new Date('2024-09-02').toISOString(),
            updatedAt: new Date('2024-09-02').toISOString(),
        },
        {
            name: 'European Roulette',
            slug: 'european-roulette',
            categoryId: 5,
            provider: 'NetEnt',
            imageUrl: '/games/european-roulette.jpg',
            thumbnailUrl: '/games/thumbs/european-roulette.jpg',
            description: 'Classic roulette with single zero for better odds',
            minBet: 0.10,
            maxBet: 1000.00,
            rtp: 97.30,
            isFeatured: false,
            isActive: true,
            playCount: 22800,
            createdAt: new Date('2024-09-14').toISOString(),
            updatedAt: new Date('2024-09-14').toISOString(),
        },
        {
            name: 'Baccarat Pro',
            slug: 'baccarat-pro',
            categoryId: 5,
            provider: "Play'n GO",
            imageUrl: '/games/baccarat-pro.jpg',
            thumbnailUrl: '/games/thumbs/baccarat-pro.jpg',
            description: 'Professional baccarat with side bet options',
            minBet: 1.00,
            maxBet: 500.00,
            rtp: 98.94,
            isFeatured: false,
            isActive: true,
            playCount: 16900,
            createdAt: new Date('2024-09-28').toISOString(),
            updatedAt: new Date('2024-09-28').toISOString(),
        },
        {
            name: 'Texas Hold\'em Bonus',
            slug: 'texas-holdem-bonus',
            categoryId: 5,
            provider: 'NetEnt',
            imageUrl: '/games/texas-holdem-bonus.jpg',
            thumbnailUrl: '/games/thumbs/texas-holdem-bonus.jpg',
            description: 'Poker variant with bonus bet and progressive jackpot',
            minBet: 1.00,
            maxBet: 200.00,
            rtp: 97.80,
            isFeatured: false,
            isActive: true,
            playCount: 14200,
            createdAt: new Date('2024-10-12').toISOString(),
            updatedAt: new Date('2024-10-12').toISOString(),
        },
        {
            name: 'Three Card Poker',
            slug: 'three-card-poker',
            categoryId: 5,
            provider: "Play'n GO",
            imageUrl: '/games/three-card-poker.jpg',
            thumbnailUrl: '/games/thumbs/three-card-poker.jpg',
            description: 'Fast poker game with pair plus side bet',
            minBet: 1.00,
            maxBet: 300.00,
            rtp: 96.63,
            isFeatured: false,
            isActive: true,
            playCount: 12700,
            createdAt: new Date('2024-10-26').toISOString(),
            updatedAt: new Date('2024-10-26').toISOString(),
        },
        {
            name: 'Caribbean Stud Poker',
            slug: 'caribbean-stud-poker',
            categoryId: 5,
            provider: 'NetEnt',
            imageUrl: '/games/caribbean-stud-poker.jpg',
            thumbnailUrl: '/games/thumbs/caribbean-stud-poker.jpg',
            description: 'Five-card stud poker with progressive jackpot',
            minBet: 1.00,
            maxBet: 200.00,
            rtp: 96.30,
            isFeatured: false,
            isActive: true,
            playCount: 10800,
            createdAt: new Date('2024-11-09').toISOString(),
            updatedAt: new Date('2024-11-09').toISOString(),
        },
        {
            name: 'Red Dog',
            slug: 'red-dog',
            categoryId: 5,
            provider: 'NetEnt',
            imageUrl: '/games/red-dog.jpg',
            thumbnailUrl: '/games/thumbs/red-dog.jpg',
            description: 'Simple card game betting on spread between cards',
            minBet: 1.00,
            maxBet: 100.00,
            rtp: 97.00,
            isFeatured: false,
            isActive: true,
            playCount: 8400,
            createdAt: new Date('2024-11-23').toISOString(),
            updatedAt: new Date('2024-11-23').toISOString(),
        },
        {
            name: 'Oasis Poker',
            slug: 'oasis-poker',
            categoryId: 5,
            provider: 'NetEnt',
            imageUrl: '/games/oasis-poker.jpg',
            thumbnailUrl: '/games/thumbs/oasis-poker.jpg',
            description: 'Caribbean stud variant with card exchange option',
            minBet: 1.00,
            maxBet: 200.00,
            rtp: 96.50,
            isFeatured: false,
            isActive: true,
            playCount: 9600,
            createdAt: new Date('2024-12-08').toISOString(),
            updatedAt: new Date('2024-12-08').toISOString(),
        },

        // Fishing Games (categoryId: 6) - 5 games
        {
            name: 'Fishing God',
            slug: 'fishing-god',
            categoryId: 6,
            provider: 'JILI',
            imageUrl: '/games/fishing-god.jpg',
            thumbnailUrl: '/games/thumbs/fishing-god.jpg',
            description: 'Shoot fish with powerful weapons for big rewards',
            minBet: 0.10,
            maxBet: 100.00,
            rtp: 95.00,
            isFeatured: false,
            isActive: true,
            playCount: 15600,
            createdAt: new Date('2024-09-06').toISOString(),
            updatedAt: new Date('2024-09-06').toISOString(),
        },
        {
            name: 'Royal Fishing',
            slug: 'royal-fishing',
            categoryId: 6,
            provider: 'JILI',
            imageUrl: '/games/royal-fishing.jpg',
            thumbnailUrl: '/games/thumbs/royal-fishing.jpg',
            description: 'Underwater adventure with royal fish and multipliers',
            minBet: 0.10,
            maxBet: 100.00,
            rtp: 96.00,
            isFeatured: false,
            isActive: true,
            playCount: 17200,
            createdAt: new Date('2024-09-24').toISOString(),
            updatedAt: new Date('2024-09-24').toISOString(),
        },
        {
            name: 'Bombing Fishing',
            slug: 'bombing-fishing',
            categoryId: 6,
            provider: 'JILI',
            imageUrl: '/games/bombing-fishing.jpg',
            thumbnailUrl: '/games/thumbs/bombing-fishing.jpg',
            description: 'Use bombs to catch multiple fish at once',
            minBet: 0.10,
            maxBet: 100.00,
            rtp: 95.50,
            isFeatured: false,
            isActive: true,
            playCount: 13800,
            createdAt: new Date('2024-10-14').toISOString(),
            updatedAt: new Date('2024-10-14').toISOString(),
        },
        {
            name: 'Dinosaur Tycoon',
            slug: 'dinosaur-tycoon',
            categoryId: 6,
            provider: 'JILI',
            imageUrl: '/games/dinosaur-tycoon.jpg',
            thumbnailUrl: '/games/thumbs/dinosaur-tycoon.jpg',
            description: 'Hunt prehistoric creatures for massive prizes',
            minBet: 0.10,
            maxBet: 100.00,
            rtp: 95.80,
            isFeatured: false,
            isActive: true,
            playCount: 12400,
            createdAt: new Date('2024-11-04').toISOString(),
            updatedAt: new Date('2024-11-04').toISOString(),
        },
        {
            name: 'Fortune Gems',
            slug: 'fortune-gems',
            categoryId: 6,
            provider: 'JILI',
            imageUrl: '/games/fortune-gems.jpg',
            thumbnailUrl: '/games/thumbs/fortune-gems.jpg',
            description: 'Collect precious gems in this shooting adventure',
            minBet: 0.10,
            maxBet: 100.00,
            rtp: 96.00,
            isFeatured: false,
            isActive: true,
            playCount: 14900,
            createdAt: new Date('2024-11-22').toISOString(),
            updatedAt: new Date('2024-11-22').toISOString(),
        },

        // Arcade (categoryId: 7) - 4 games
        {
            name: 'Hi-Lo',
            slug: 'hi-lo',
            categoryId: 7,
            provider: 'Spribe',
            imageUrl: '/games/hi-lo.jpg',
            thumbnailUrl: '/games/thumbs/hi-lo.jpg',
            description: 'Guess if next card is higher or lower',
            minBet: 0.10,
            maxBet: 100.00,
            rtp: 97.00,
            isFeatured: false,
            isActive: true,
            playCount: 11200,
            createdAt: new Date('2024-10-04').toISOString(),
            updatedAt: new Date('2024-10-04').toISOString(),
        },
        {
            name: 'Hotline',
            slug: 'hotline',
            categoryId: 7,
            provider: 'Spribe',
            imageUrl: '/games/hotline.jpg',
            thumbnailUrl: '/games/thumbs/hotline.jpg',
            description: 'Fast-paced arcade game with instant wins',
            minBet: 0.10,
            maxBet: 100.00,
            rtp: 97.00,
            isFeatured: false,
            isActive: true,
            playCount: 9800,
            createdAt: new Date('2024-10-28').toISOString(),
            updatedAt: new Date('2024-10-28').toISOString(),
        },
        {
            name: 'Keno',
            slug: 'keno',
            categoryId: 7,
            provider: 'Spribe',
            imageUrl: '/games/keno.jpg',
            thumbnailUrl: '/games/thumbs/keno.jpg',
            description: 'Pick numbers and watch balls drop for wins',
            minBet: 0.10,
            maxBet: 100.00,
            rtp: 97.00,
            isFeatured: false,
            isActive: true,
            playCount: 13500,
            createdAt: new Date('2024-11-14').toISOString(),
            updatedAt: new Date('2024-11-14').toISOString(),
        },
        {
            name: 'Turbo Plinko',
            slug: 'turbo-plinko',
            categoryId: 7,
            provider: 'Spribe',
            imageUrl: '/games/turbo-plinko.jpg',
            thumbnailUrl: '/games/thumbs/turbo-plinko.jpg',
            description: 'Faster plinko with turbo mode for quick wins',
            minBet: 0.10,
            maxBet: 100.00,
            rtp: 97.00,
            isFeatured: false,
            isActive: true,
            playCount: 16700,
            createdAt: new Date('2024-12-02').toISOString(),
            updatedAt: new Date('2024-12-02').toISOString(),
        },
    ];

    await db.insert(games).values(sampleGames);
    
    console.log('✅ Games seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});