import { db } from '@/db';
import { transactions } from '@/db/schema';

async function main() {
    const sampleTransactions = [
        // User 1 - High roller (15 transactions)
        {
            userId: 1,
            type: 'deposit',
            amount: 2000.00,
            balanceBefore: 0,
            balanceAfter: 2000.00,
            status: 'completed',
            paymentMethod: 'Credit Card',
            transactionRef: 'DEP-ABC123XYZ',
            description: 'Deposit via Credit Card',
            createdAt: new Date('2024-01-15T10:30:00').toISOString(),
            completedAt: new Date('2024-01-15T10:32:00').toISOString(),
        },
        {
            userId: 1,
            type: 'bet',
            amount: -500.00,
            balanceBefore: 2000.00,
            balanceAfter: 1500.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Sweet Bonanza',
            createdAt: new Date('2024-02-01T14:20:00').toISOString(),
            completedAt: new Date('2024-02-01T14:20:00').toISOString(),
        },
        {
            userId: 1,
            type: 'win',
            amount: 1000.00,
            balanceBefore: 1500.00,
            balanceAfter: 2500.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Win from Sweet Bonanza',
            createdAt: new Date('2024-02-01T14:22:00').toISOString(),
            completedAt: new Date('2024-02-01T14:22:00').toISOString(),
        },
        {
            userId: 1,
            type: 'deposit',
            amount: 1500.00,
            balanceBefore: 2500.00,
            balanceAfter: 4000.00,
            status: 'completed',
            paymentMethod: 'Crypto',
            transactionRef: 'DEP-CRY456789',
            description: 'Deposit via Crypto',
            createdAt: new Date('2024-01-20T16:45:00').toISOString(),
            completedAt: new Date('2024-01-20T16:55:00').toISOString(),
        },
        {
            userId: 1,
            type: 'bet',
            amount: -300.00,
            balanceBefore: 4000.00,
            balanceAfter: 3700.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Gates of Olympus',
            createdAt: new Date('2024-02-05T11:15:00').toISOString(),
            completedAt: new Date('2024-02-05T11:15:00').toISOString(),
        },
        {
            userId: 1,
            type: 'bet',
            amount: -250.00,
            balanceBefore: 3700.00,
            balanceAfter: 3450.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Book of Dead',
            createdAt: new Date('2024-02-06T09:30:00').toISOString(),
            completedAt: new Date('2024-02-06T09:30:00').toISOString(),
        },
        {
            userId: 1,
            type: 'win',
            amount: 750.00,
            balanceBefore: 3450.00,
            balanceAfter: 4200.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Win from Book of Dead',
            createdAt: new Date('2024-02-06T09:32:00').toISOString(),
            completedAt: new Date('2024-02-06T09:32:00').toISOString(),
        },
        {
            userId: 1,
            type: 'withdrawal',
            amount: -1500.00,
            balanceBefore: 4200.00,
            balanceAfter: 2700.00,
            status: 'completed',
            paymentMethod: 'Bank Transfer',
            transactionRef: 'WD-XYZ789ABC',
            description: 'Withdrawal to Bank Transfer',
            createdAt: new Date('2024-02-10T13:00:00').toISOString(),
            completedAt: new Date('2024-02-10T15:30:00').toISOString(),
        },
        {
            userId: 1,
            type: 'bonus',
            amount: 100.00,
            balanceBefore: 2700.00,
            balanceAfter: 2700.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: 'BONUS-WELCOME100',
            description: 'Bonus credited: Welcome Bonus',
            createdAt: new Date('2024-01-25T12:00:00').toISOString(),
            completedAt: new Date('2024-01-25T12:00:00').toISOString(),
        },
        {
            userId: 1,
            type: 'bet',
            amount: -400.00,
            balanceBefore: 2700.00,
            balanceAfter: 2300.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Aviator',
            createdAt: new Date('2024-02-12T17:20:00').toISOString(),
            completedAt: new Date('2024-02-12T17:20:00').toISOString(),
        },
        {
            userId: 1,
            type: 'deposit',
            amount: 1000.00,
            balanceBefore: 2300.00,
            balanceAfter: 3300.00,
            status: 'completed',
            paymentMethod: 'E-Wallet',
            transactionRef: 'DEP-EW123456',
            description: 'Deposit via E-Wallet',
            createdAt: new Date('2024-02-01T08:00:00').toISOString(),
            completedAt: new Date('2024-02-01T08:05:00').toISOString(),
        },
        {
            userId: 1,
            type: 'bet',
            amount: -350.00,
            balanceBefore: 3300.00,
            balanceAfter: 2950.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Crazy Time',
            createdAt: new Date('2024-02-13T19:45:00').toISOString(),
            completedAt: new Date('2024-02-13T19:45:00').toISOString(),
        },
        {
            userId: 1,
            type: 'win',
            amount: 700.00,
            balanceBefore: 2950.00,
            balanceAfter: 3650.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Win from Crazy Time',
            createdAt: new Date('2024-02-13T19:47:00').toISOString(),
            completedAt: new Date('2024-02-13T19:47:00').toISOString(),
        },
        {
            userId: 1,
            type: 'bet',
            amount: -200.00,
            balanceBefore: 3650.00,
            balanceAfter: 3450.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Gonzo\'s Quest',
            createdAt: new Date('2024-02-14T10:00:00').toISOString(),
            completedAt: new Date('2024-02-14T10:00:00').toISOString(),
        },
        {
            userId: 1,
            type: 'withdrawal',
            amount: -800.00,
            balanceBefore: 3450.00,
            balanceAfter: 2650.00,
            status: 'pending',
            paymentMethod: 'Crypto',
            transactionRef: 'WD-CRY987654',
            description: 'Withdrawal to Crypto',
            createdAt: new Date('2024-02-14T14:30:00').toISOString(),
            completedAt: null,
        },

        // User 2 - Medium player (10 transactions)
        {
            userId: 2,
            type: 'deposit',
            amount: 500.00,
            balanceBefore: 0,
            balanceAfter: 500.00,
            status: 'completed',
            paymentMethod: 'PayPal',
            transactionRef: 'DEP-PP789456',
            description: 'Deposit via PayPal',
            createdAt: new Date('2024-01-18T11:00:00').toISOString(),
            completedAt: new Date('2024-01-18T11:02:00').toISOString(),
        },
        {
            userId: 2,
            type: 'bet',
            amount: -50.00,
            balanceBefore: 500.00,
            balanceAfter: 450.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Starburst',
            createdAt: new Date('2024-02-02T15:30:00').toISOString(),
            completedAt: new Date('2024-02-02T15:30:00').toISOString(),
        },
        {
            userId: 2,
            type: 'win',
            amount: 150.00,
            balanceBefore: 450.00,
            balanceAfter: 600.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Win from Starburst',
            createdAt: new Date('2024-02-02T15:35:00').toISOString(),
            completedAt: new Date('2024-02-02T15:35:00').toISOString(),
        },
        {
            userId: 2,
            type: 'deposit',
            amount: 300.00,
            balanceBefore: 600.00,
            balanceAfter: 900.00,
            status: 'completed',
            paymentMethod: 'Credit Card',
            transactionRef: 'DEP-CC456123',
            description: 'Deposit via Credit Card',
            createdAt: new Date('2024-01-25T09:15:00').toISOString(),
            completedAt: new Date('2024-01-25T09:17:00').toISOString(),
        },
        {
            userId: 2,
            type: 'bet',
            amount: -75.00,
            balanceBefore: 900.00,
            balanceAfter: 825.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Mega Moolah',
            createdAt: new Date('2024-02-08T12:00:00').toISOString(),
            completedAt: new Date('2024-02-08T12:00:00').toISOString(),
        },
        {
            userId: 2,
            type: 'bet',
            amount: -100.00,
            balanceBefore: 825.00,
            balanceAfter: 725.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Lightning Roulette',
            createdAt: new Date('2024-02-10T18:30:00').toISOString(),
            completedAt: new Date('2024-02-10T18:30:00').toISOString(),
        },
        {
            userId: 2,
            type: 'bonus',
            amount: 50.00,
            balanceBefore: 725.00,
            balanceAfter: 725.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: 'BONUS-RELOAD50',
            description: 'Bonus credited: Reload Bonus',
            createdAt: new Date('2024-01-30T14:00:00').toISOString(),
            completedAt: new Date('2024-01-30T14:00:00').toISOString(),
        },
        {
            userId: 2,
            type: 'bet',
            amount: -80.00,
            balanceBefore: 725.00,
            balanceAfter: 645.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Blackjack',
            createdAt: new Date('2024-02-11T20:15:00').toISOString(),
            completedAt: new Date('2024-02-11T20:15:00').toISOString(),
        },
        {
            userId: 2,
            type: 'withdrawal',
            amount: -200.00,
            balanceBefore: 645.00,
            balanceAfter: 445.00,
            status: 'completed',
            paymentMethod: 'E-Wallet',
            transactionRef: 'WD-EW456789',
            description: 'Withdrawal to E-Wallet',
            createdAt: new Date('2024-02-12T10:00:00').toISOString(),
            completedAt: new Date('2024-02-12T13:00:00').toISOString(),
        },
        {
            userId: 2,
            type: 'deposit',
            amount: 250.00,
            balanceBefore: 445.00,
            balanceAfter: 695.00,
            status: 'pending',
            paymentMethod: 'Bank Transfer',
            transactionRef: 'DEP-BT789123',
            description: 'Deposit via Bank Transfer',
            createdAt: new Date('2024-02-14T08:00:00').toISOString(),
            completedAt: null,
        },

        // User 3 - Regular player (8 transactions)
        {
            userId: 3,
            type: 'deposit',
            amount: 200.00,
            balanceBefore: 0,
            balanceAfter: 200.00,
            status: 'completed',
            paymentMethod: 'E-Wallet',
            transactionRef: 'DEP-EW321654',
            description: 'Deposit via E-Wallet',
            createdAt: new Date('2024-01-22T13:30:00').toISOString(),
            completedAt: new Date('2024-01-22T13:32:00').toISOString(),
        },
        {
            userId: 3,
            type: 'bet',
            amount: -25.00,
            balanceBefore: 200.00,
            balanceAfter: 175.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Book of Ra',
            createdAt: new Date('2024-02-03T16:00:00').toISOString(),
            completedAt: new Date('2024-02-03T16:00:00').toISOString(),
        },
        {
            userId: 3,
            type: 'bet',
            amount: -30.00,
            balanceBefore: 175.00,
            balanceAfter: 145.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Wolf Gold',
            createdAt: new Date('2024-02-05T14:30:00').toISOString(),
            completedAt: new Date('2024-02-05T14:30:00').toISOString(),
        },
        {
            userId: 3,
            type: 'win',
            amount: 90.00,
            balanceBefore: 145.00,
            balanceAfter: 235.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Win from Wolf Gold',
            createdAt: new Date('2024-02-05T14:35:00').toISOString(),
            completedAt: new Date('2024-02-05T14:35:00').toISOString(),
        },
        {
            userId: 3,
            type: 'deposit',
            amount: 150.00,
            balanceBefore: 235.00,
            balanceAfter: 385.00,
            status: 'completed',
            paymentMethod: 'Credit Card',
            transactionRef: 'DEP-CC987321',
            description: 'Deposit via Credit Card',
            createdAt: new Date('2024-02-01T10:00:00').toISOString(),
            completedAt: new Date('2024-02-01T10:03:00').toISOString(),
        },
        {
            userId: 3,
            type: 'bet',
            amount: -40.00,
            balanceBefore: 385.00,
            balanceAfter: 345.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Reactoonz',
            createdAt: new Date('2024-02-09T11:20:00').toISOString(),
            completedAt: new Date('2024-02-09T11:20:00').toISOString(),
        },
        {
            userId: 3,
            type: 'bonus',
            amount: 25.00,
            balanceBefore: 345.00,
            balanceAfter: 345.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: 'BONUS-DEPOSIT25',
            description: 'Bonus credited: Deposit Match Bonus',
            createdAt: new Date('2024-02-02T15:00:00').toISOString(),
            completedAt: new Date('2024-02-02T15:00:00').toISOString(),
        },
        {
            userId: 3,
            type: 'bet',
            amount: -45.00,
            balanceBefore: 345.00,
            balanceAfter: 300.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Dead or Alive',
            createdAt: new Date('2024-02-13T09:00:00').toISOString(),
            completedAt: new Date('2024-02-13T09:00:00').toISOString(),
        },

        // User 4 - Casual player (6 transactions)
        {
            userId: 4,
            type: 'deposit',
            amount: 100.00,
            balanceBefore: 0,
            balanceAfter: 100.00,
            status: 'completed',
            paymentMethod: 'PayPal',
            transactionRef: 'DEP-PP654987',
            description: 'Deposit via PayPal',
            createdAt: new Date('2024-01-28T14:00:00').toISOString(),
            completedAt: new Date('2024-01-28T14:02:00').toISOString(),
        },
        {
            userId: 4,
            type: 'bet',
            amount: -10.00,
            balanceBefore: 100.00,
            balanceAfter: 90.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Fruit Shop',
            createdAt: new Date('2024-02-04T17:30:00').toISOString(),
            completedAt: new Date('2024-02-04T17:30:00').toISOString(),
        },
        {
            userId: 4,
            type: 'bet',
            amount: -15.00,
            balanceBefore: 90.00,
            balanceAfter: 75.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Thunderstruck II',
            createdAt: new Date('2024-02-07T19:00:00').toISOString(),
            completedAt: new Date('2024-02-07T19:00:00').toISOString(),
        },
        {
            userId: 4,
            type: 'win',
            amount: 45.00,
            balanceBefore: 75.00,
            balanceAfter: 120.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Win from Thunderstruck II',
            createdAt: new Date('2024-02-07T19:05:00').toISOString(),
            completedAt: new Date('2024-02-07T19:05:00').toISOString(),
        },
        {
            userId: 4,
            type: 'deposit',
            amount: 80.00,
            balanceBefore: 120.00,
            balanceAfter: 200.00,
            status: 'completed',
            paymentMethod: 'Crypto',
            transactionRef: 'DEP-CRY147258',
            description: 'Deposit via Crypto',
            createdAt: new Date('2024-02-05T11:00:00').toISOString(),
            completedAt: new Date('2024-02-05T11:10:00').toISOString(),
        },
        {
            userId: 4,
            type: 'bet',
            amount: -20.00,
            balanceBefore: 200.00,
            balanceAfter: 180.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Immortal Romance',
            createdAt: new Date('2024-02-11T15:45:00').toISOString(),
            completedAt: new Date('2024-02-11T15:45:00').toISOString(),
        },

        // User 5 - New player (5 transactions)
        {
            userId: 5,
            type: 'deposit',
            amount: 50.00,
            balanceBefore: 0,
            balanceAfter: 50.00,
            status: 'completed',
            paymentMethod: 'Credit Card',
            transactionRef: 'DEP-CC159753',
            description: 'Deposit via Credit Card',
            createdAt: new Date('2024-02-01T12:00:00').toISOString(),
            completedAt: new Date('2024-02-01T12:02:00').toISOString(),
        },
        {
            userId: 5,
            type: 'bonus',
            amount: 50.00,
            balanceBefore: 50.00,
            balanceAfter: 50.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: 'BONUS-WELCOME50',
            description: 'Bonus credited: New Player Welcome',
            createdAt: new Date('2024-02-01T12:05:00').toISOString(),
            completedAt: new Date('2024-02-01T12:05:00').toISOString(),
        },
        {
            userId: 5,
            type: 'bet',
            amount: -5.00,
            balanceBefore: 50.00,
            balanceAfter: 45.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Cleopatra',
            createdAt: new Date('2024-02-06T16:30:00').toISOString(),
            completedAt: new Date('2024-02-06T16:30:00').toISOString(),
        },
        {
            userId: 5,
            type: 'bet',
            amount: -10.00,
            balanceBefore: 45.00,
            balanceAfter: 35.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Twin Spin',
            createdAt: new Date('2024-02-10T13:15:00').toISOString(),
            completedAt: new Date('2024-02-10T13:15:00').toISOString(),
        },
        {
            userId: 5,
            type: 'deposit',
            amount: 75.00,
            balanceBefore: 35.00,
            balanceAfter: 110.00,
            status: 'completed',
            paymentMethod: 'E-Wallet',
            transactionRef: 'DEP-EW852963',
            description: 'Deposit via E-Wallet',
            createdAt: new Date('2024-02-12T09:00:00').toISOString(),
            completedAt: new Date('2024-02-12T09:03:00').toISOString(),
        },

        // User 6 - Medium player (7 transactions)
        {
            userId: 6,
            type: 'deposit',
            amount: 300.00,
            balanceBefore: 0,
            balanceAfter: 300.00,
            status: 'completed',
            paymentMethod: 'Bank Transfer',
            transactionRef: 'DEP-BT753159',
            description: 'Deposit via Bank Transfer',
            createdAt: new Date('2024-01-19T10:30:00').toISOString(),
            completedAt: new Date('2024-01-19T10:45:00').toISOString(),
        },
        {
            userId: 6,
            type: 'bet',
            amount: -60.00,
            balanceBefore: 300.00,
            balanceAfter: 240.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Bonanza',
            createdAt: new Date('2024-02-03T14:00:00').toISOString(),
            completedAt: new Date('2024-02-03T14:00:00').toISOString(),
        },
        {
            userId: 6,
            type: 'bet',
            amount: -35.00,
            balanceBefore: 240.00,
            balanceAfter: 205.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Fire Joker',
            createdAt: new Date('2024-02-08T18:20:00').toISOString(),
            completedAt: new Date('2024-02-08T18:20:00').toISOString(),
        },
        {
            userId: 6,
            type: 'win',
            amount: 105.00,
            balanceBefore: 205.00,
            balanceAfter: 310.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Win from Fire Joker',
            createdAt: new Date('2024-02-08T18:25:00').toISOString(),
            completedAt: new Date('2024-02-08T18:25:00').toISOString(),
        },
        {
            userId: 6,
            type: 'deposit',
            amount: 200.00,
            balanceBefore: 310.00,
            balanceAfter: 510.00,
            status: 'completed',
            paymentMethod: 'Crypto',
            transactionRef: 'DEP-CRY369258',
            description: 'Deposit via Crypto',
            createdAt: new Date('2024-02-06T12:00:00').toISOString(),
            completedAt: new Date('2024-02-06T12:08:00').toISOString(),
        },
        {
            userId: 6,
            type: 'bet',
            amount: -70.00,
            balanceBefore: 510.00,
            balanceAfter: 440.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Jammin\' Jars',
            createdAt: new Date('2024-02-12T16:30:00').toISOString(),
            completedAt: new Date('2024-02-12T16:30:00').toISOString(),
        },
        {
            userId: 6,
            type: 'withdrawal',
            amount: -150.00,
            balanceBefore: 440.00,
            balanceAfter: 290.00,
            status: 'completed',
            paymentMethod: 'Bank Transfer',
            transactionRef: 'WD-BT159357',
            description: 'Withdrawal to Bank Transfer',
            createdAt: new Date('2024-02-13T11:00:00').toISOString(),
            completedAt: new Date('2024-02-13T14:30:00').toISOString(),
        },

        // User 7 - Light player (5 transactions)
        {
            userId: 7,
            type: 'deposit',
            amount: 75.00,
            balanceBefore: 0,
            balanceAfter: 75.00,
            status: 'completed',
            paymentMethod: 'PayPal',
            transactionRef: 'DEP-PP951753',
            description: 'Deposit via PayPal',
            createdAt: new Date('2024-01-30T15:00:00').toISOString(),
            completedAt: new Date('2024-01-30T15:02:00').toISOString(),
        },
        {
            userId: 7,
            type: 'bet',
            amount: -12.00,
            balanceBefore: 75.00,
            balanceAfter: 63.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Vikings Go Berzerk',
            createdAt: new Date('2024-02-05T10:30:00').toISOString(),
            completedAt: new Date('2024-02-05T10:30:00').toISOString(),
        },
        {
            userId: 7,
            type: 'bet',
            amount: -8.00,
            balanceBefore: 63.00,
            balanceAfter: 55.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Piggy Riches',
            createdAt: new Date('2024-02-09T14:00:00').toISOString(),
            completedAt: new Date('2024-02-09T14:00:00').toISOString(),
        },
        {
            userId: 7,
            type: 'win',
            amount: 24.00,
            balanceBefore: 55.00,
            balanceAfter: 79.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Win from Piggy Riches',
            createdAt: new Date('2024-02-09T14:03:00').toISOString(),
            completedAt: new Date('2024-02-09T14:03:00').toISOString(),
        },
        {
            userId: 7,
            type: 'bet',
            amount: -15.00,
            balanceBefore: 79.00,
            balanceAfter: 64.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Rainbow Riches',
            createdAt: new Date('2024-02-13T17:20:00').toISOString(),
            completedAt: new Date('2024-02-13T17:20:00').toISOString(),
        },

        // User 8 - Active player (9 transactions)
        {
            userId: 8,
            type: 'deposit',
            amount: 400.00,
            balanceBefore: 0,
            balanceAfter: 400.00,
            status: 'completed',
            paymentMethod: 'Credit Card',
            transactionRef: 'DEP-CC357951',
            description: 'Deposit via Credit Card',
            createdAt: new Date('2024-01-20T09:00:00').toISOString(),
            completedAt: new Date('2024-01-20T09:02:00').toISOString(),
        },
        {
            userId: 8,
            type: 'bet',
            amount: -80.00,
            balanceBefore: 400.00,
            balanceAfter: 320.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Razor Shark',
            createdAt: new Date('2024-02-02T13:45:00').toISOString(),
            completedAt: new Date('2024-02-02T13:45:00').toISOString(),
        },
        {
            userId: 8,
            type: 'win',
            amount: 240.00,
            balanceBefore: 320.00,
            balanceAfter: 560.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Win from Razor Shark',
            createdAt: new Date('2024-02-02T13:50:00').toISOString(),
            completedAt: new Date('2024-02-02T13:50:00').toISOString(),
        },
        {
            userId: 8,
            type: 'bet',
            amount: -50.00,
            balanceBefore: 560.00,
            balanceAfter: 510.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Money Train',
            createdAt: new Date('2024-02-07T11:00:00').toISOString(),
            completedAt: new Date('2024-02-07T11:00:00').toISOString(),
        },
        {
            userId: 8,
            type: 'deposit',
            amount: 250.00,
            balanceBefore: 510.00,
            balanceAfter: 760.00,
            status: 'completed',
            paymentMethod: 'E-Wallet',
            transactionRef: 'DEP-EW741852',
            description: 'Deposit via E-Wallet',
            createdAt: new Date('2024-02-03T14:30:00').toISOString(),
            completedAt: new Date('2024-02-03T14:33:00').toISOString(),
        },
        {
            userId: 8,
            type: 'bet',
            amount: -90.00,
            balanceBefore: 760.00,
            balanceAfter: 670.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Big Bass Bonanza',
            createdAt: new Date('2024-02-10T16:15:00').toISOString(),
            completedAt: new Date('2024-02-10T16:15:00').toISOString(),
        },
        {
            userId: 8,
            type: 'withdrawal',
            amount: -300.00,
            balanceBefore: 670.00,
            balanceAfter: 370.00,
            status: 'completed',
            paymentMethod: 'Crypto',
            transactionRef: 'WD-CRY753951',
            description: 'Withdrawal to Crypto',
            createdAt: new Date('2024-02-11T10:00:00').toISOString(),
            completedAt: new Date('2024-02-11T11:30:00').toISOString(),
        },
        {
            userId: 8,
            type: 'bonus',
            amount: 25.00,
            balanceBefore: 370.00,
            balanceAfter: 370.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: 'BONUS-CASHBACK25',
            description: 'Bonus credited: Weekly Cashback',
            createdAt: new Date('2024-02-08T12:00:00').toISOString(),
            completedAt: new Date('2024-02-08T12:00:00').toISOString(),
        },
        {
            userId: 8,
            type: 'bet',
            amount: -65.00,
            balanceBefore: 370.00,
            balanceAfter: 305.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on The Dog House',
            createdAt: new Date('2024-02-14T09:30:00').toISOString(),
            completedAt: new Date('2024-02-14T09:30:00').toISOString(),
        },

        // User 9 - Regular player (6 transactions)
        {
            userId: 9,
            type: 'deposit',
            amount: 180.00,
            balanceBefore: 0,
            balanceAfter: 180.00,
            status: 'completed',
            paymentMethod: 'Bank Transfer',
            transactionRef: 'DEP-BT258741',
            description: 'Deposit via Bank Transfer',
            createdAt: new Date('2024-01-25T11:00:00').toISOString(),
            completedAt: new Date('2024-01-25T11:15:00').toISOString(),
        },
        {
            userId: 9,
            type: 'bet',
            amount: -30.00,
            balanceBefore: 180.00,
            balanceAfter: 150.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Gorilla Kingdom',
            createdAt: new Date('2024-02-04T15:00:00').toISOString(),
            completedAt: new Date('2024-02-04T15:00:00').toISOString(),
        },
        {
            userId: 9,
            type: 'bet',
            amount: -22.00,
            balanceBefore: 150.00,
            balanceAfter: 128.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Buffalo King',
            createdAt: new Date('2024-02-08T12:30:00').toISOString(),
            completedAt: new Date('2024-02-08T12:30:00').toISOString(),
        },
        {
            userId: 9,
            type: 'win',
            amount: 66.00,
            balanceBefore: 128.00,
            balanceAfter: 194.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Win from Buffalo King',
            createdAt: new Date('2024-02-08T12:35:00').toISOString(),
            completedAt: new Date('2024-02-08T12:35:00').toISOString(),
        },
        {
            userId: 9,
            type: 'deposit',
            amount: 120.00,
            balanceBefore: 194.00,
            balanceAfter: 314.00,
            status: 'completed',
            paymentMethod: 'PayPal',
            transactionRef: 'DEP-PP147369',
            description: 'Deposit via PayPal',
            createdAt: new Date('2024-02-10T09:00:00').toISOString(),
            completedAt: new Date('2024-02-10T09:02:00').toISOString(),
        },
        {
            userId: 9,
            type: 'bet',
            amount: -38.00,
            balanceBefore: 314.00,
            balanceAfter: 276.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Punk Rocker',
            createdAt: new Date('2024-02-13T14:45:00').toISOString(),
            completedAt: new Date('2024-02-13T14:45:00').toISOString(),
        },

        // User 10 - Moderate player (7 transactions)
        {
            userId: 10,
            type: 'deposit',
            amount: 350.00,
            balanceBefore: 0,
            balanceAfter: 350.00,
            status: 'completed',
            paymentMethod: 'Crypto',
            transactionRef: 'DEP-CRY951357',
            description: 'Deposit via Crypto',
            createdAt: new Date('2024-01-21T13:00:00').toISOString(),
            completedAt: new Date('2024-01-21T13:10:00').toISOString(),
        },
        {
            userId: 10,
            type: 'bet',
            amount: -55.00,
            balanceBefore: 350.00,
            balanceAfter: 295.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on San Quentin',
            createdAt: new Date('2024-02-03T17:30:00').toISOString(),
            completedAt: new Date('2024-02-03T17:30:00').toISOString(),
        },
        {
            userId: 10,
            type: 'win',
            amount: 165.00,
            balanceBefore: 295.00,
            balanceAfter: 460.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Win from San Quentin',
            createdAt: new Date('2024-02-03T17:35:00').toISOString(),
            completedAt: new Date('2024-02-03T17:35:00').toISOString(),
        },
        {
            userId: 10,
            type: 'bet',
            amount: -48.00,
            balanceBefore: 460.00,
            balanceAfter: 412.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Tombstone',
            createdAt: new Date('2024-02-07T10:15:00').toISOString(),
            completedAt: new Date('2024-02-07T10:15:00').toISOString(),
        },
        {
            userId: 10,
            type: 'deposit',
            amount: 200.00,
            balanceBefore: 412.00,
            balanceAfter: 612.00,
            status: 'completed',
            paymentMethod: 'E-Wallet',
            transactionRef: 'DEP-EW159753',
            description: 'Deposit via E-Wallet',
            createdAt: new Date('2024-02-09T08:00:00').toISOString(),
            completedAt: new Date('2024-02-09T08:03:00').toISOString(),
        },
        {
            userId: 10,
            type: 'bet',
            amount: -72.00,
            balanceBefore: 612.00,
            balanceAfter: 540.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on El Paso Gunfight',
            createdAt: new Date('2024-02-12T15:00:00').toISOString(),
            completedAt: new Date('2024-02-12T15:00:00').toISOString(),
        },
        {
            userId: 10,
            type: 'withdrawal',
            amount: -250.00,
            balanceBefore: 540.00,
            balanceAfter: 290.00,
            status: 'pending',
            paymentMethod: 'Bank Transfer',
            transactionRef: 'WD-BT357159',
            description: 'Withdrawal to Bank Transfer',
            createdAt: new Date('2024-02-14T11:00:00').toISOString(),
            completedAt: null,
        },

        // User 11 - Light player (5 transactions)
        {
            userId: 11,
            type: 'deposit',
            amount: 60.00,
            balanceBefore: 0,
            balanceAfter: 60.00,
            status: 'completed',
            paymentMethod: 'Credit Card',
            transactionRef: 'DEP-CC753159',
            description: 'Deposit via Credit Card',
            createdAt: new Date('2024-01-29T16:00:00').toISOString(),
            completedAt: new Date('2024-01-29T16:02:00').toISOString(),
        },
        {
            userId: 11,
            type: 'bet',
            amount: -8.00,
            balanceBefore: 60.00,
            balanceAfter: 52.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Joker Stoker',
            createdAt: new Date('2024-02-05T13:20:00').toISOString(),
            completedAt: new Date('2024-02-05T13:20:00').toISOString(),
        },
        {
            userId: 11,
            type: 'bet',
            amount: -6.00,
            balanceBefore: 52.00,
            balanceAfter: 46.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Gems Bonanza',
            createdAt: new Date('2024-02-09T18:45:00').toISOString(),
            completedAt: new Date('2024-02-09T18:45:00').toISOString(),
        },
        {
            userId: 11,
            type: 'win',
            amount: 18.00,
            balanceBefore: 46.00,
            balanceAfter: 64.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Win from Gems Bonanza',
            createdAt: new Date('2024-02-09T18:50:00').toISOString(),
            completedAt: new Date('2024-02-09T18:50:00').toISOString(),
        },
        {
            userId: 11,
            type: 'deposit',
            amount: 40.00,
            balanceBefore: 64.00,
            balanceAfter: 104.00,
            status: 'completed',
            paymentMethod: 'PayPal',
            transactionRef: 'DEP-PP963852',
            description: 'Deposit via PayPal',
            createdAt: new Date('2024-02-11T10:30:00').toISOString(),
            completedAt: new Date('2024-02-11T10:32:00').toISOString(),
        },

        // User 12 - Active player (8 transactions)
        {
            userId: 12,
            type: 'deposit',
            amount: 450.00,
            balanceBefore: 0,
            balanceAfter: 450.00,
            status: 'completed',
            paymentMethod: 'Bank Transfer',
            transactionRef: 'DEP-BT852963',
            description: 'Deposit via Bank Transfer',
            createdAt: new Date('2024-01-17T10:00:00').toISOString(),
            completedAt: new Date('2024-01-17T10:20:00').toISOString(),
        },
        {
            userId: 12,
            type: 'bet',
            amount: -85.00,
            balanceBefore: 450.00,
            balanceAfter: 365.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Safari Gold',
            createdAt: new Date('2024-02-02T11:00:00').toISOString(),
            completedAt: new Date('2024-02-02T11:00:00').toISOString(),
        },
        {
            userId: 12,
            type: 'bet',
            amount: -42.00,
            balanceBefore: 365.00,
            balanceAfter: 323.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Wild Falls',
            createdAt: new Date('2024-02-06T14:30:00').toISOString(),
            completedAt: new Date('2024-02-06T14:30:00').toISOString(),
        },
        {
            userId: 12,
            type: 'win',
            amount: 126.00,
            balanceBefore: 323.00,
            balanceAfter: 449.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Win from Wild Falls',
            createdAt: new Date('2024-02-06T14:35:00').toISOString(),
            completedAt: new Date('2024-02-06T14:35:00').toISOString(),
        },
        {
            userId: 12,
            type: 'deposit',
            amount: 280.00,
            balanceBefore: 449.00,
            balanceAfter: 729.00,
            status: 'completed',
            paymentMethod: 'Crypto',
            transactionRef: 'DEP-CRY654789',
            description: 'Deposit via Crypto',
            createdAt: new Date('2024-02-04T09:00:00').toISOString(),
            completedAt: new Date('2024-02-04T09:10:00').toISOString(),
        },
        {
            userId: 12,
            type: 'bet',
            amount: -95.00,
            balanceBefore: 729.00,
            balanceAfter: 634.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Buffalo Blitz',
            createdAt: new Date('2024-02-10T17:00:00').toISOString(),
            completedAt: new Date('2024-02-10T17:00:00').toISOString(),
        },
        {
            userId: 12,
            type: 'withdrawal',
            amount: -400.00,
            balanceBefore: 634.00,
            balanceAfter: 234.00,
            status: 'completed',
            paymentMethod: 'E-Wallet',
            transactionRef: 'WD-EW951357',
            description: 'Withdrawal to E-Wallet',
            createdAt: new Date('2024-02-11T13:00:00').toISOString(),
            completedAt: new Date('2024-02-11T16:00:00').toISOString(),
        },
        {
            userId: 12,
            type: 'bonus',
            amount: 10.00,
            balanceBefore: 234.00,
            balanceAfter: 234.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: 'BONUS-FREESPIN10',
            description: 'Bonus credited: Free Spins Bonus',
            createdAt: new Date('2024-02-07T12:00:00').toISOString(),
            completedAt: new Date('2024-02-07T12:00:00').toISOString(),
        },

        // User 13 - Casual player (5 transactions)
        {
            userId: 13,
            type: 'deposit',
            amount: 90.00,
            balanceBefore: 0,
            balanceAfter: 90.00,
            status: 'completed',
            paymentMethod: 'E-Wallet',
            transactionRef: 'DEP-EW369147',
            description: 'Deposit via E-Wallet',
            createdAt: new Date('2024-02-02T15:00:00').toISOString(),
            completedAt: new Date('2024-02-02T15:03:00').toISOString(),
        },
        {
            userId: 13,
            type: 'bet',
            amount: -14.00,
            balanceBefore: 90.00,
            balanceAfter: 76.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Phoenix Fire',
            createdAt: new Date('2024-02-06T16:00:00').toISOString(),
            completedAt: new Date('2024-02-06T16:00:00').toISOString(),
        },
        {
            userId: 13,
            type: 'bet',
            amount: -18.00,
            balanceBefore: 76.00,
            balanceAfter: 58.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Zombie Circus',
            createdAt: new Date('2024-02-10T19:30:00').toISOString(),
            completedAt: new Date('2024-02-10T19:30:00').toISOString(),
        },
        {
            userId: 13,
            type: 'refund',
            amount: 10.00,
            balanceBefore: 58.00,
            balanceAfter: 68.00,
            status: 'completed',
            paymentMethod: 'E-Wallet',
            transactionRef: 'DEP-EW369147',
            description: 'Refund for transaction DEP-EW369147',
            createdAt: new Date('2024-02-12T10:00:00').toISOString(),
            completedAt: new Date('2024-02-12T10:00:00').toISOString(),
        },
        {
            userId: 13,
            type: 'deposit',
            amount: 65.00,
            balanceBefore: 68.00,
            balanceAfter: 133.00,
            status: 'completed',
            paymentMethod: 'Credit Card',
            transactionRef: 'DEP-CC741258',
            description: 'Deposit via Credit Card',
            createdAt: new Date('2024-02-13T11:00:00').toISOString(),
            completedAt: new Date('2024-02-13T11:02:00').toISOString(),
        },

        // User 14 - Regular player (6 transactions)
        {
            userId: 14,
            type: 'deposit',
            amount: 270.00,
            balanceBefore: 0,
            balanceAfter: 270.00,
            status: 'completed',
            paymentMethod: 'PayPal',
            transactionRef: 'DEP-PP258963',
            description: 'Deposit via PayPal',
            createdAt: new Date('2024-01-23T12:00:00').toISOString(),
            completedAt: new Date('2024-01-23T12:02:00').toISOString(),
        },
        {
            userId: 14,
            type: 'bet',
            amount: -45.00,
            balanceBefore: 270.00,
            balanceAfter: 225.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Mystery Reels',
            createdAt: new Date('2024-02-04T14:15:00').toISOString(),
            completedAt: new Date('2024-02-04T14:15:00').toISOString(),
        },
        {
            userId: 14,
            type: 'win',
            amount: 135.00,
            balanceBefore: 225.00,
            balanceAfter: 360.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Win from Mystery Reels',
            createdAt: new Date('2024-02-04T14:20:00').toISOString(),
            completedAt: new Date('2024-02-04T14:20:00').toISOString(),
        },
        {
            userId: 14,
            type: 'bet',
            amount: -52.00,
            balanceBefore: 360.00,
            balanceAfter: 308.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Dragon\'s Fire',
            createdAt: new Date('2024-02-09T16:00:00').toISOString(),
            completedAt: new Date('2024-02-09T16:00:00').toISOString(),
        },
        {
            userId: 14,
            type: 'deposit',
            amount: 150.00,
            balanceBefore: 308.00,
            balanceAfter: 458.00,
            status: 'completed',
            paymentMethod: 'Bank Transfer',
            transactionRef: 'DEP-BT963741',
            description: 'Deposit via Bank Transfer',
            createdAt: new Date('2024-02-08T10:00:00').toISOString(),
            completedAt: new Date('2024-02-08T10:15:00').toISOString(),
        },
        {
            userId: 14,
            type: 'bet',
            amount: -38.00,
            balanceBefore: 458.00,
            balanceAfter: 420.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Golden Ticket',
            createdAt: new Date('2024-02-13T12:30:00').toISOString(),
            completedAt: new Date('2024-02-13T12:30:00').toISOString(),
        },

        // User 15 - Medium player (7 transactions)
        {
            userId: 15,
            type: 'deposit',
            amount: 320.00,
            balanceBefore: 0,
            balanceAfter: 320.00,
            status: 'completed',
            paymentMethod: 'Crypto',
            transactionRef: 'DEP-CRY147963',
            description: 'Deposit via Crypto',
            createdAt: new Date('2024-01-24T14:00:00').toISOString(),
            completedAt: new Date('2024-01-24T14:10:00').toISOString(),
        },
        {
            userId: 15,
            type: 'bet',
            amount: -62.00,
            balanceBefore: 320.00,
            balanceAfter: 258.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Wild Swarm',
            createdAt: new Date('2024-02-03T11:30:00').toISOString(),
            completedAt: new Date('2024-02-03T11:30:00').toISOString(),
        },
        {
            userId: 15,
            type: 'bet',
            amount: -33.00,
            balanceBefore: 258.00,
            balanceAfter: 225.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Planet Fortune',
            createdAt: new Date('2024-02-07T15:45:00').toISOString(),
            completedAt: new Date('2024-02-07T15:45:00').toISOString(),
        },
        {
            userId: 15,
            type: 'win',
            amount: 99.00,
            balanceBefore: 225.00,
            balanceAfter: 324.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Win from Planet Fortune',
            createdAt: new Date('2024-02-07T15:50:00').toISOString(),
            completedAt: new Date('2024-02-07T15:50:00').toISOString(),
        },
        {
            userId: 15,
            type: 'deposit',
            amount: 190.00,
            balanceBefore: 324.00,
            balanceAfter: 514.00,
            status: 'completed',
            paymentMethod: 'E-Wallet',
            transactionRef: 'DEP-EW753951',
            description: 'Deposit via E-Wallet',
            createdAt: new Date('2024-02-09T09:00:00').toISOString(),
            completedAt: new Date('2024-02-09T09:03:00').toISOString(),
        },
        {
            userId: 15,
            type: 'bet',
            amount: -76.00,
            balanceBefore: 514.00,
            balanceAfter: 438.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Temple Tumble',
            createdAt: new Date('2024-02-12T18:00:00').toISOString(),
            completedAt: new Date('2024-02-12T18:00:00').toISOString(),
        },
        {
            userId: 15,
            type: 'withdrawal',
            amount: -180.00,
            balanceBefore: 438.00,
            balanceAfter: 258.00,
            status: 'completed',
            paymentMethod: 'Bank Transfer',
            transactionRef: 'WD-BT654321',
            description: 'Withdrawal to Bank Transfer',
            createdAt: new Date('2024-02-13T14:00:00').toISOString(),
            completedAt: new Date('2024-02-13T17:00:00').toISOString(),
        },

        // User 16 - Light player (4 transactions)
        {
            userId: 16,
            type: 'deposit',
            amount: 55.00,
            balanceBefore: 0,
            balanceAfter: 55.00,
            status: 'completed',
            paymentMethod: 'Credit Card',
            transactionRef: 'DEP-CC159357',
            description: 'Deposit via Credit Card',
            createdAt: new Date('2024-02-03T17:00:00').toISOString(),
            completedAt: new Date('2024-02-03T17:02:00').toISOString(),
        },
        {
            userId: 16,
            type: 'bet',
            amount: -7.00,
            balanceBefore: 55.00,
            balanceAfter: 48.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Lucky Leprechaun',
            createdAt: new Date('2024-02-08T13:00:00').toISOString(),
            completedAt: new Date('2024-02-08T13:00:00').toISOString(),
        },
        {
            userId: 16,
            type: 'bet',
            amount: -9.00,
            balanceBefore: 48.00,
            balanceAfter: 39.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Jungle Spirit',
            createdAt: new Date('2024-02-11T16:30:00').toISOString(),
            completedAt: new Date('2024-02-11T16:30:00').toISOString(),
        },
        {
            userId: 16,
            type: 'deposit',
            amount: 45.00,
            balanceBefore: 39.00,
            balanceAfter: 84.00,
            status: 'failed',
            paymentMethod: 'PayPal',
            transactionRef: 'DEP-PP852741',
            description: 'Deposit via PayPal',
            createdAt: new Date('2024-02-14T10:00:00').toISOString(),
            completedAt: new Date('2024-02-14T10:05:00').toISOString(),
        },

        // User 17 - Regular player (6 transactions)
        {
            userId: 17,
            type: 'deposit',
            amount: 380.00,
            balanceBefore: 0,
            balanceAfter: 380.00,
            status: 'completed',
            paymentMethod: 'Bank Transfer',
            transactionRef: 'DEP-BT456789',
            description: 'Deposit via Bank Transfer',
            createdAt: new Date('2024-01-26T11:30:00').toISOString(),
            completedAt: new Date('2024-01-26T11:45:00').toISOString(),
        },
        {
            userId: 17,
            type: 'bet',
            amount: -68.00,
            balanceBefore: 380.00,
            balanceAfter: 312.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Arctic Magic',
            createdAt: new Date('2024-02-05T12:00:00').toISOString(),
            completedAt: new Date('2024-02-05T12:00:00').toISOString(),
        },
        {
            userId: 17,
            type: 'win',
            amount: 204.00,
            balanceBefore: 312.00,
            balanceAfter: 516.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Win from Arctic Magic',
            createdAt: new Date('2024-02-05T12:05:00').toISOString(),
            completedAt: new Date('2024-02-05T12:05:00').toISOString(),
        },
        {
            userId: 17,
            type: 'bet',
            amount: -44.00,
            balanceBefore: 516.00,
            balanceAfter: 472.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Crystal Queen',
            createdAt: new Date('2024-02-10T14:30:00').toISOString(),
            completedAt: new Date('2024-02-10T14:30:00').toISOString(),
        },
        {
            userId: 17,
            type: 'deposit',
            amount: 160.00,
            balanceBefore: 472.00,
            balanceAfter: 632.00,
            status: 'completed',
            paymentMethod: 'Crypto',
            transactionRef: 'DEP-CRY852147',
            description: 'Deposit via Crypto',
            createdAt: new Date('2024-02-11T08:00:00').toISOString(),
            completedAt: new Date('2024-02-11T08:10:00').toISOString(),
        },
        {
            userId: 17,
            type: 'bet',
            amount: -58.00,
            balanceBefore: 632.00,
            balanceAfter: 574.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Atlantis Megaways',
            createdAt: new Date('2024-02-14T16:00:00').toISOString(),
            completedAt: new Date('2024-02-14T16:00:00').toISOString(),
        },

        // User 18 - Active player (8 transactions)
        {
            userId: 18,
            type: 'deposit',
            amount: 520.00,
            balanceBefore: 0,
            balanceAfter: 520.00,
            status: 'completed',
            paymentMethod: 'E-Wallet',
            transactionRef: 'DEP-EW963258',
            description: 'Deposit via E-Wallet',
            createdAt: new Date('2024-01-19T09:30:00').toISOString(),
            completedAt: new Date('2024-01-19T09:33:00').toISOString(),
        },
        {
            userId: 18,
            type: 'bet',
            amount: -92.00,
            balanceBefore: 520.00,
            balanceAfter: 428.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Vikings Unleashed',
            createdAt: new Date('2024-02-02T10:00:00').toISOString(),
            completedAt: new Date('2024-02-02T10:00:00').toISOString(),
        },
        {
            userId: 18,
            type: 'win',
            amount: 276.00,
            balanceBefore: 428.00,
            balanceAfter: 704.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Win from Vikings Unleashed',
            createdAt: new Date('2024-02-02T10:05:00').toISOString(),
            completedAt: new Date('2024-02-02T10:05:00').toISOString(),
        },
        {
            userId: 18,
            type: 'bet',
            amount: -56.00,
            balanceBefore: 704.00,
            balanceAfter: 648.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Aztec Gems',
            createdAt: new Date('2024-02-06T13:30:00').toISOString(),
            completedAt: new Date('2024-02-06T13:30:00').toISOString(),
        },
        {
            userId: 18,
            type: 'deposit',
            amount: 310.00,
            balanceBefore: 648.00,
            balanceAfter: 958.00,
            status: 'completed',
            paymentMethod: 'Credit Card',
            transactionRef: 'DEP-CC741963',
            description: 'Deposit via Credit Card',
            createdAt: new Date('2024-02-07T11:00:00').toISOString(),
            completedAt: new Date('2024-02-07T11:02:00').toISOString(),
        },
        {
            userId: 18,
            type: 'bet',
            amount: -88.00,
            balanceBefore: 958.00,
            balanceAfter: 870.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Primal Megaways',
            createdAt: new Date('2024-02-11T17:00:00').toISOString(),
            completedAt: new Date('2024-02-11T17:00:00').toISOString(),
        },
        {
            userId: 18,
            type: 'withdrawal',
            amount: -500.00,
            balanceBefore: 870.00,
            balanceAfter: 370.00,
            status: 'completed',
            paymentMethod: 'E-Wallet',
            transactionRef: 'WD-EW741852',
            description: 'Withdrawal to E-Wallet',
            createdAt: new Date('2024-02-12T09:00:00').toISOString(),
            completedAt: new Date('2024-02-12T12:00:00').toISOString(),
        },
        {
            userId: 18,
            type: 'bonus',
            amount: 10.00,
            balanceBefore: 370.00,
            balanceAfter: 370.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: 'BONUS-LOYALTY10',
            description: 'Bonus credited: Loyalty Reward',
            createdAt: new Date('2024-02-10T12:00:00').toISOString(),
            completedAt: new Date('2024-02-10T12:00:00').toISOString(),
        },

        // User 19 - Light player (4 transactions)
        {
            userId: 19,
            type: 'deposit',
            amount: 70.00,
            balanceBefore: 0,
            balanceAfter: 70.00,
            status: 'completed',
            paymentMethod: 'PayPal',
            transactionRef: 'DEP-PP321789',
            description: 'Deposit via PayPal',
            createdAt: new Date('2024-02-04T14:00:00').toISOString(),
            completedAt: new Date('2024-02-04T14:02:00').toISOString(),
        },
        {
            userId: 19,
            type: 'bet',
            amount: -11.00,
            balanceBefore: 70.00,
            balanceAfter: 59.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Easter Island',
            createdAt: new Date('2024-02-09T15:30:00').toISOString(),
            completedAt: new Date('2024-02-09T15:30:00').toISOString(),
        },
        {
            userId: 19,
            type: 'win',
            amount: 33.00,
            balanceBefore: 59.00,
            balanceAfter: 92.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Win from Easter Island',
            createdAt: new Date('2024-02-09T15:35:00').toISOString(),
            completedAt: new Date('2024-02-09T15:35:00').toISOString(),
        },
        {
            userId: 19,
            type: 'bet',
            amount: -16.00,
            balanceBefore: 92.00,
            balanceAfter: 76.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Dragon Shrine',
            createdAt: new Date('2024-02-13T18:00:00').toISOString(),
            completedAt: new Date('2024-02-13T18:00:00').toISOString(),
        },

        // User 20 - Moderate player (7 transactions)
        {
            userId: 20,
            type: 'deposit',
            amount: 410.00,
            balanceBefore: 0,
            balanceAfter: 410.00,
            status: 'completed',
            paymentMethod: 'Crypto',
            transactionRef: 'DEP-CRY789456',
            description: 'Deposit via Crypto',
            createdAt: new Date('2024-01-22T10:00:00').toISOString(),
            completedAt: new Date('2024-01-22T10:10:00').toISOString(),
        },
        {
            userId: 20,
            type: 'bet',
            amount: -74.00,
            balanceBefore: 410.00,
            balanceAfter: 336.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Solar Queen',
            createdAt: new Date('2024-02-04T11:30:00').toISOString(),
            completedAt: new Date('2024-02-04T11:30:00').toISOString(),
        },
        {
            userId: 20,
            type: 'win',
            amount: 222.00,
            balanceBefore: 336.00,
            balanceAfter: 558.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Win from Solar Queen',
            createdAt: new Date('2024-02-04T11:35:00').toISOString(),
            completedAt: new Date('2024-02-04T11:35:00').toISOString(),
        },
        {
            userId: 20,
            type: 'bet',
            amount: -51.00,
            balanceBefore: 558.00,
            balanceAfter: 507.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Emerald King',
            createdAt: new Date('2024-02-08T16:00:00').toISOString(),
            completedAt: new Date('2024-02-08T16:00:00').toISOString(),
        },
        {
            userId: 20,
            type: 'deposit',
            amount: 220.00,
            balanceBefore: 507.00,
            balanceAfter: 727.00,
            status: 'completed',
            paymentMethod: 'Bank Transfer',
            transactionRef: 'DEP-BT147852',
            description: 'Deposit via Bank Transfer',
            createdAt: new Date('2024-02-10T09:00:00').toISOString(),
            completedAt: new Date('2024-02-10T09:15:00').toISOString(),
        },
        {
            userId: 20,
            type: 'bet',
            amount: -82.00,
            balanceBefore: 727.00,
            balanceAfter: 645.00,
            status: 'completed',
            paymentMethod: null,
            transactionRef: null,
            description: 'Bet placed on Super Flip',
            createdAt: new Date('2024-02-13T10:30:00').toISOString(),
            completedAt: new Date('2024-02-13T10:30:00').toISOString(),
        },
        {
            userId: 20,
            type: 'refund',
            amount: 25.00,
            balanceBefore: 645.00,
            balanceAfter: 670.00,
            status: 'completed',
            paymentMethod: 'Bank Transfer',
            transactionRef: 'DEP-BT147852',
            description: 'Refund for transaction DEP-BT147852',
            createdAt: new Date('2024-02-14T11:00:00').toISOString(),
            completedAt: new Date('2024-02-14T11:00:00').toISOString(),
        },
    ];

    await db.insert(transactions).values(sampleTransactions);
    
    console.log('✅ Transactions seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});